import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Kelompok A', groupB: 'Kelompok B', mean: 'Rata-rata', standardDeviation: 'Simpangan baku sampel', sampleSize: 'Ukuran sampel', meanHelp: 'Hasil rata-rata kelompok ini.', standardDeviationHelp: 'Gunakan simpangan baku sampel, bukan galat baku.', sampleSizeHelp: 'Minimal 2 observasi.', example: 'Gunakan contoh', reset: 'Atur ulang', clear: 'Hapus input', resultTitle: 'Interpretasi efek', difference: 'Selisih rata-rata A dikurangi B', pooledStandardDeviation: 'SD gabungan', degreesOfFreedom: 'Derajat kebebasan', cohensD: 'd Cohen', hedgesG: 'g Hedges', correction: 'Koreksi sampel kecil', confidenceInterval: 'Perkiraan CI 95%', magnitude: 'Besaran', direction: 'Arah', uncertainty: 'Presisi', higher: 'Kelompok A lebih tinggi', lower: 'Kelompok A lebih rendah', equal: 'Rata-rata sama', verySmall: 'Sangat kecil', small: 'Kecil', medium: 'Sedang', large: 'Besar', crossesZero: 'Interval melintasi nol', doesNotCrossZero: 'Interval tidak melintasi nol', chartTitle: 'Selisih pada skala bersama', chartDifference: 'Selisih mentah', chartBand: 'Interval g Hedges', chartBaseline: 'Rata-rata sama', chartA: 'Rata-rata kelompok A', chartB: 'Rata-rata kelompok B', chartEmpty: 'Masukkan enam nilai yang valid untuk melihat selisih.', statusReady: 'Diperbarui dari nilai di atas.', statusInvalid: 'Periksa keenam kolom: SD harus positif dan ukuran sampel minimal 2.', statusCopied: 'Ringkasan disalin.', copied: 'Tersalin', inputError: 'Nilai tidak valid', summaryTitle: 'Ringkasan ukuran efek dua kelompok', copySummary: 'Salin ringkasan',
};

export const content = makeEffectContent({ language: 'id', slug: 'kalkulator-ukuran-efek-dua-kelompok', title: 'Kalkulator Ukuran Efek Dua Kelompok', description: 'Hitung d Cohen dan g Hedges dari ringkasan dua kelompok independen, lalu tafsirkan arah, besaran, dan perkiraan interval kepercayaan 95%.', ui,
  faq: [
    { question: 'Apa yang diukur d Cohen?', answer: 'd Cohen menyatakan perbedaan dua rata-rata dalam satuan simpangan baku gabungan. Tandanya mempertahankan arah A dikurangi B, sedangkan nilai absolutnya menunjukkan besaran standar.' },
    { question: 'Mengapa g Hedges juga ditampilkan?', answer: 'g Hedges menerapkan koreksi sampel kecil pada d Cohen. Koreksinya kecil untuk kelompok besar dan lebih terlihat ketika derajat kebebasan gabungan sedikit.' },
    { question: 'Apakah interval yang melintasi nol membuktikan tidak ada efek?', answer: 'Tidak. Itu berarti interval perkiraan 95% mencakup nol sehingga arah efek belum presisi pada tingkat tersebut. Ini bukan bukti kesetaraan atau ketiadaan efek.' },
    { question: 'Apakah kalkulator ini menggantikan uji t atau meta-analisis?', answer: 'Tidak. Kalkulator ini menghitung perbedaan standar dari statistik ringkasan; ia tidak menguji hipotesis, memeriksa asumsi, menangani data berpasangan, atau menggabungkan studi.' },
  ],
  howTo: [
    { name: 'Masukkan ringkasan kedua kelompok', text: 'Masukkan rata-rata, simpangan baku sampel, dan ukuran setiap kelompok. Gunakan skala yang sama dan tentukan A serta B sebelum membaca tandanya.' },
    { name: 'Baca perbedaan standar', text: 'Gunakan d Cohen untuk estimasi langsung dan g Hedges untuk estimasi dengan koreksi sampel kecil. Hasilnya mempertahankan arah A dikurangi B.' },
    { name: 'Periksa presisi dan konteks', text: 'Baca interval kepercayaan perkiraan 95% bersama kategori besaran. Ambang hanyalah panduan, bukan aturan universal.' },
  ],
  introTitle: 'Standarkan perbedaan sebelum menafsirkannya', introOne: 'Perbedaan mentah antara rata-rata bergantung pada skala pengukuran. <strong>Kalkulator ukuran efek dua kelompok</strong> ini membagi perbedaan dengan simpangan baku gabungan sehingga jarak dinyatakan dalam satuan simpangan baku.', introTwo: 'Masukkan ringkasan dua kelompok independen: rata-rata, simpangan baku sampel, dan ukuran sampel. Alat ini menghasilkan d Cohen, g Hedges yang dikoreksi untuk sampel kecil, perkiraan interval 95%, dan arah A dikurangi B.', calculationTitle: 'Yang digunakan dalam perhitungan', tableHeaders: ['Hasil', 'Cara membacanya'], tableRows: [['Perbedaan rata-rata', 'Perbedaan asli A dikurangi B dalam satuan pengukuran.'], ['Simpangan baku gabungan', 'Penyebaran bersama yang digunakan untuk menstandarkan perbedaan.'], ['d Cohen', 'Perbedaan standar sebelum koreksi sampel kecil.'], ['g Hedges', 'd Cohen dikalikan koreksi berdasarkan derajat kebebasan gabungan.'], ['Interval perkiraan 95%', 'Interval presisi berdasarkan statistik ringkasan dan pendekatan normal.']], directionTitle: 'Cara membaca arah', direction: 'Tanda sangat penting. Nilai positif berarti rata-rata A lebih besar daripada B; nilai negatif berarti sebaliknya. Menukar kelompok mengubah tanda, bukan besaran absolut.', actions: ['Pertahankan kedua kelompok pada skala yang sama.', 'Gunakan simpangan baku sampel, bukan galat baku.', 'Pastikan observasi bersifat independen.', 'Laporkan estimasi, interval, urutan kelompok, dan satuan.'], thresholdTitle: 'Ambang bukan keputusan mutlak', threshold: 'Label sangat kecil, kecil, sedang, dan besar mengikuti acuan umum sekitar 0,2, 0,5, dan 0,8. Arti praktis bergantung pada hasil, kualitas pengukuran, desain, dan perbedaan minimum yang penting.', precisionTitle: 'Presisi adalah bagian dari hasil', precision: 'Perbedaan standar yang besar dengan interval lebar tetap dapat tidak presisi, terutama pada kelompok kecil atau sangat bervariasi. Jika interval g Hedges melintasi nol, anggap arahnya belum pasti pada tingkat perkiraan ini.', glossaryTitle: 'Glosarium', glossary: [['Simpangan baku gabungan', 'Estimasi penyebaran bersama dua kelompok independen yang disesuaikan dengan ukuran sampel.'], ['d Cohen', 'Perbedaan rata-rata dibagi simpangan baku gabungan.'], ['g Hedges', 'Perbedaan standar yang dikoreksi untuk bias sampel kecil.'], ['Interval kepercayaan', 'Rentang yang menunjukkan ketidakpastian estimasi, bukan jaminan tentang parameter tetap.']], limitsTitle: 'Yang tidak dapat diberitahukan alat ini', limits: 'Kalkulator ini tidak membuktikan kausalitas, signifikansi statistik, kesetaraan, arti klinis, kenormalan, kesamaan varians, atau kualitas studi. Kalkulator ini tidak mendukung observasi berpasangan dan tidak dapat memulihkan informasi yang hilang dari statistik ringkasan saja.',
});
