import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Gruppo A', groupB: 'Gruppo B', mean: 'Media', standardDeviation: 'Deviazione standard campionaria', sampleSize: 'Dimensione del campione', meanHelp: 'Risultato medio di questo gruppo.', standardDeviationHelp: 'Usa la DS campionaria, non l\u0027errore standard.', sampleSizeHelp: 'Almeno 2 osservazioni.', example: 'Usa esempio', reset: 'Reimposta', clear: 'Cancella dati', resultTitle: 'Lettura dell\u0027effetto', difference: 'Differenza delle medie A meno B', pooledStandardDeviation: 'DS combinata', degreesOfFreedom: 'Gradi di libertà', cohensD: 'd di Cohen', hedgesG: 'g di Hedges', correction: 'Correzione per campioni piccoli', confidenceInterval: 'IC 95% circa', magnitude: 'Magnitudo', direction: 'Direzione', uncertainty: 'Precisione', higher: 'Il gruppo A è maggiore', lower: 'Il gruppo A è minore', equal: 'Le medie sono uguali', verySmall: 'Molto piccola', small: 'Piccola', medium: 'Media', large: 'Grande', crossesZero: 'L\u0027intervallo attraversa zero', doesNotCrossZero: 'L\u0027intervallo non attraversa zero', chartTitle: 'La differenza su una scala comune', chartDifference: 'Differenza grezza', chartBand: 'Intervallo g di Hedges', chartBaseline: 'Medie uguali', chartA: 'Media gruppo A', chartB: 'Media gruppo B', chartEmpty: 'Inserisci sei valori validi per vedere la differenza.', statusReady: 'Aggiornato con i valori sopra.', statusInvalid: 'Controlla i sei campi: le DS devono essere positive e le dimensioni almeno 2.', statusCopied: 'Riepilogo copiato.', copied: 'Copiato', inputError: 'Valore non valido', summaryTitle: 'Riepilogo della dimensione dell\u0027effetto per due gruppi', copySummary: 'Copia riepilogo',
};

export const content = makeEffectContent({ language: 'it', slug: 'calcolatore-dimensione-effetto-due-gruppi', title: 'Calcolatore della dimensione dell\u0027effetto per due gruppi', description: 'Calcola d di Cohen e g di Hedges dai riepiloghi di due gruppi indipendenti e interpreta direzione, magnitudo e intervallo di confidenza approssimato al 95%.', ui,
  faq: [
    { question: 'Che cosa misura il d di Cohen?', answer: 'Il d di Cohen esprime la differenza tra due medie in unità di deviazione standard combinata. Il segno conserva la direzione A meno B, mentre il valore assoluto indica la magnitudo standardizzata.' },
    { question: 'Perché mostrare anche il g di Hedges?', answer: 'Il g di Hedges applica una correzione per campioni piccoli al d di Cohen. La correzione è modesta con gruppi grandi e più evidente quando i gradi di libertà sono pochi.' },
    { question: 'Un intervallo che attraversa zero dimostra che non c\u0027è effetto?', answer: 'No. Significa che l\u0027intervallo approssimato al 95% include zero e che la direzione non è precisa a quel livello. Non dimostra equivalenza o assenza.' },
    { question: 'Questo calcolatore sostituisce un test t o una metanalisi?', answer: 'No. Calcola differenze standardizzate da statistiche riassuntive. Non verifica ipotesi, assunzioni, dati appaiati o più studi insieme.' },
  ],
  howTo: [
    { name: 'Inserisci i riepiloghi dei due gruppi', text: 'Inserisci media, deviazione standard campionaria e dimensione di ciascun gruppo. Usa la stessa scala e definisci A e B prima di leggere il segno.' },
    { name: 'Leggi la differenza standardizzata', text: 'Usa d di Cohen per la stima diretta e g di Hedges per quella corretta per campioni piccoli. Il risultato mantiene la direzione A meno B.' },
    { name: 'Controlla precisione e contesto', text: 'Leggi insieme l\u0027intervallo approssimato al 95% e la categoria della magnitudo. Una soglia è un riferimento, non una regola universale.' },
  ],
  introTitle: 'Standardizza la differenza prima di interpretarla', introOne: 'Una differenza grezza tra medie dipende dalla scala di misura. Questo <strong>calcolatore della dimensione dell\u0027effetto per due gruppi</strong> divide la differenza per la deviazione standard combinata.', introTwo: 'Inserisci i riepiloghi di due gruppi indipendenti: media, deviazione standard campionaria e dimensione. Lo strumento restituisce d di Cohen, g di Hedges, intervalli approssimati al 95% e direzione A meno B.', calculationTitle: 'Cosa usa il calcolo', tableHeaders: ['Risultato', 'Come leggerlo'], tableRows: [['Differenza delle medie', 'La differenza originale A meno B nelle unità di misura.'], ['Deviazione standard combinata', 'La dispersione comune usata per standardizzare la differenza.'], ['d di Cohen', 'La differenza standardizzata prima della correzione per campioni piccoli.'], ['g di Hedges', 'Il d di Cohen moltiplicato per una correzione basata sui gradi di libertà.'], ['Intervallo approssimato al 95%', 'Un intervallo di precisione basato sui dati e su un\u0027approssimazione normale.']], directionTitle: 'Come leggere la direzione', direction: 'Il segno è importante. Un valore positivo indica che la media di A è maggiore di quella di B; un valore negativo indica il contrario. Invertendo i gruppi cambia il segno, non la magnitudo assoluta.', actions: ['Mantieni i gruppi sulla stessa scala.', 'Usa deviazioni standard campionarie, non errori standard.', 'Verifica che le osservazioni siano indipendenti.', 'Riporta stima, intervallo, ordine dei gruppi e unità.'], thresholdTitle: 'Le soglie non sono verdetti', threshold: 'Le etichette molto piccola, piccola, media e grande seguono riferimenti intorno a 0,2, 0,5 e 0,8. L\u0027importanza pratica dipende dal risultato, dalla misura, dal disegno e dalla differenza minima rilevante.', precisionTitle: 'La precisione fa parte del risultato', precision: 'Una differenza standardizzata grande con un intervallo ampio può essere imprecisa, soprattutto con gruppi piccoli o variabili. Se l\u0027intervallo del g di Hedges attraversa zero, considera incerta la direzione.', glossaryTitle: 'Glossario', glossary: [['Deviazione standard combinata', 'Stima della dispersione comune di due gruppi indipendenti, corretta per la dimensione dei campioni.'], ['d di Cohen', 'Differenza delle medie divisa per la deviazione standard combinata.'], ['g di Hedges', 'Versione della differenza standardizzata corretta per il bias dei campioni piccoli.'], ['Intervallo di confidenza', 'Intervallo che mostra l\u0027incertezza della stima, non una garanzia.']], limitsTitle: 'Cosa non può dirti questo strumento', limits: 'Il calcolatore non dimostra causalità, significatività statistica, equivalenza, importanza clinica, normalità, uguaglianza delle varianze o qualità dello studio. Non supporta osservazioni appaiate.',
});
