import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Groep A', groupB: 'Groep B', mean: 'Gemiddelde', standardDeviation: 'Steekproefstandaarddeviatie', sampleSize: 'Steekproefgrootte', meanHelp: 'Gemiddelde uitkomst in deze groep.', standardDeviationHelp: 'Gebruik de steekproef-SD, niet de standaardfout.', sampleSizeHelp: 'Minimaal 2 waarnemingen.', example: 'Voorbeeld gebruiken', reset: 'Herstellen', clear: 'Invoer wissen', resultTitle: 'Effectinterpretatie', difference: 'Gemiddeld verschil A min B', pooledStandardDeviation: 'Gepoolde SD', degreesOfFreedom: 'Vrijheidsgraden', cohensD: "Cohen's d", hedgesG: "Hedges' g", correction: 'Correctie voor kleine steekproef', confidenceInterval: 'Geschat 95%-BI', magnitude: 'Grootte', direction: 'Richting', uncertainty: 'Precisie', higher: 'Groep A is hoger', lower: 'Groep A is lager', equal: 'De gemiddelden zijn gelijk', verySmall: 'Zeer klein', small: 'Klein', medium: 'Gemiddeld', large: 'Groot', crossesZero: 'Interval kruist nul', doesNotCrossZero: 'Interval kruist nul niet', chartTitle: 'Het verschil op één schaal', chartDifference: 'Ruw verschil', chartBand: 'Hedges-g-interval', chartBaseline: 'Gelijke gemiddelden', chartA: 'Gemiddelde groep A', chartB: 'Gemiddelde groep B', chartEmpty: 'Voer zes geldige waarden in om het verschil te zien.', statusReady: 'Bijgewerkt met de waarden hierboven.', statusInvalid: 'Controleer de zes velden: SD\u0027s moeten positief zijn en steekproeven minimaal 2 bevatten.', statusCopied: 'Samenvatting gekopieerd.', copied: 'Gekopieerd', inputError: 'Ongeldige invoer', summaryTitle: 'Samenvatting effectgrootte voor twee groepen', copySummary: 'Samenvatting kopiëren',
};

export const content = makeEffectContent({ language: 'nl', slug: 'effectgrootte-twee-groepen-calculator', title: 'Calculator voor effectgrootte van twee groepen', description: 'Bereken Cohen\u0027s d en Hedges\u0027 g op basis van samenvattingen van twee onafhankelijke groepen en bekijk richting, grootte en het geschatte 95%-betrouwbaarheidsinterval.', ui,
  faq: [
    { question: "Wat meet Cohen\u0027s d?", answer: "Cohen\u0027s d geeft het verschil tussen twee groepsgemiddelden weer in eenheden van de gepoolde standaarddeviatie. Het teken bewaart A min B en de absolute waarde de gestandaardiseerde grootte." },
    { question: "Waarom Hedges' g naast Cohen's d?", answer: "Hedges' g corrigeert Cohen's d voor kleine steekproeven. Bij grote groepen is die correctie klein; bij weinig gecombineerde vrijheidsgraden valt ze meer op." },
    { question: 'Bewijst een interval dat nul kruist dat er geen effect is?', answer: 'Nee. Het geschatte 95%-interval bevat nul, waardoor de richting op dit niveau niet precies is. Dat bewijst geen equivalentie of afwezigheid.' },
    { question: 'Vervangt deze calculator een t-toets of meta-analyse?', answer: 'Nee. De tool berekent een gestandaardiseerd verschil uit samenvattende statistieken. Hij toetst geen hypothesen en combineert geen studies.' },
  ],
  howTo: [
    { name: 'Voer de samenvattingen in', text: 'Voer voor elke groep het gemiddelde, de steekproef-SD en de steekproefgrootte in. Gebruik dezelfde schaal en bepaal A en B voordat je het teken leest.' },
    { name: 'Lees het gestandaardiseerde verschil', text: "Gebruik Cohen's d voor de directe schatting en Hedges' g voor de correctie bij kleine steekproeven. De richting blijft A min B." },
    { name: 'Controleer precisie en context', text: 'Lees het geschatte 95%-interval samen met de grootteklasse. Een drempel is een richtlijn, geen universele regel.' },
  ],
  introTitle: 'Standaardiseer het verschil voordat je het interpreteert', introOne: 'Een ruw verschil tussen gemiddelden hangt af van de meetschaal. Deze <strong>calculator voor effectgrootte van twee groepen</strong> deelt het verschil door de gepoolde standaarddeviatie.', introTwo: 'Voer voor twee onafhankelijke groepen het gemiddelde, de steekproef-SD en de steekproefgrootte in. De tool geeft Cohen\u0027s d, Hedges\u0027 g, geschatte 95%-intervallen en de richting A min B.', calculationTitle: 'Wat de berekening gebruikt', tableHeaders: ['Uitkomst', 'Zo lees je die'], tableRows: [['Gemiddeld verschil', 'Het oorspronkelijke verschil A min B in de meeteenheden.'], ['Gepoolde standaarddeviatie', 'De gemeenschappelijke spreiding om het verschil te standaardiseren.'], ["Cohen's d", 'Het gestandaardiseerde verschil vóór de correctie voor kleine steekproeven.'], ["Hedges' g", 'Cohen d vermenigvuldigd met een correctie op basis van de vrijheidsgraden.'], ['Geschat 95%-interval', 'Een precisiebereik op basis van de samenvattingen en een normale benadering.']], directionTitle: 'De richting lezen', direction: 'Het teken is betekenisvol. Een positieve waarde betekent dat A een hoger gemiddelde heeft dan B; een negatieve waarde betekent het omgekeerde. Als je de groepen omwisselt, draait het teken om maar blijft de absolute grootte gelijk.', actions: ['Houd beide groepen op dezelfde meetschaal.', 'Gebruik steekproef-SD\u0027s, geen standaardfouten.', 'Controleer of de waarnemingen onafhankelijk zijn.', 'Rapporteer schatting, interval, groepsvolgorde en eenheden.'], thresholdTitle: 'Drempels zijn geen uitspraken', threshold: 'De labels zeer klein, klein, gemiddeld en groot volgen gangbare punten rond 0,2, 0,5 en 0,8. Praktische betekenis hangt af van uitkomst, meetkwaliteit, onderzoeksopzet en de relevante minimale afwijking.', precisionTitle: 'Precisie hoort bij de uitkomst', precision: 'Een groot gestandaardiseerd verschil met een breed interval kan nog steeds onnauwkeurig zijn, vooral bij kleine of variabele groepen. Als het Hedges-g-interval nul kruist, is de richting onzeker.', glossaryTitle: 'Woordenlijst', glossary: [['Gepoolde standaarddeviatie', 'Een op steekproefgrootte aangepaste schatting van de gezamenlijke spreiding.'], ["Cohen's d", 'Het gemiddeld verschil gedeeld door de gepoolde standaarddeviatie.'], ["Hedges' g", 'Een voor kleine steekproeven gecorrigeerde gestandaardiseerde gemiddelde verschilscore.'], ['Betrouwbaarheidsinterval', 'Een bereik dat onzekerheid rond de schatting toont, geen garantie.']], limitsTitle: 'Wat deze tool niet kan vertellen', limits: 'Deze calculator bewijst geen causaliteit, statistische significantie, equivalentie, klinische relevantie, normaliteit, gelijke varianties of onderzoekskwaliteit. Gepaarde waarnemingen worden niet ondersteund.',
});
