import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Grupa A', groupB: 'Grupa B', mean: 'Średnia', standardDeviation: 'Odchylenie standardowe z próby', sampleSize: 'Liczebność próby', meanHelp: 'Średni wynik w tej grupie.', standardDeviationHelp: 'Użyj odchylenia z próby, nie błędu standardowego.', sampleSizeHelp: 'Co najmniej 2 obserwacje.', example: 'Użyj przykładu', reset: 'Resetuj', clear: 'Wyczyść dane', resultTitle: 'Odczyt efektu', difference: 'Różnica średnich A minus B', pooledStandardDeviation: 'Połączone odchylenie standardowe', degreesOfFreedom: 'Stopnie swobody', cohensD: "d Cohena", hedgesG: "g Hedgesa", correction: 'Korekta dla małych prób', confidenceInterval: 'Przybliżony 95% PU', magnitude: 'Wielkość', direction: 'Kierunek', uncertainty: 'Precyzja', higher: 'Grupa A jest wyższa', lower: 'Grupa A jest niższa', equal: 'Średnie są równe', verySmall: 'Bardzo mała', small: 'Mała', medium: 'Średnia', large: 'Duża', crossesZero: 'Przedział obejmuje zero', doesNotCrossZero: 'Przedział nie obejmuje zera', chartTitle: 'Różnica na wspólnej skali', chartDifference: 'Różnica surowa', chartBand: 'Przedział g Hedgesa', chartBaseline: 'Równe średnie', chartA: 'Średnia grupy A', chartB: 'Średnia grupy B', chartEmpty: 'Wpisz sześć poprawnych wartości, aby zobaczyć skalibrowaną różnicę.', statusReady: 'Zaktualizowano na podstawie powyższych wartości.', statusInvalid: 'Sprawdź sześć pól: odchylenia muszą być dodatnie, a liczebności wynosić co najmniej 2.', statusCopied: 'Skopiowano podsumowanie.', copied: 'Skopiowano', inputError: 'Nieprawidłowa wartość', summaryTitle: 'Podsumowanie wielkości efektu dla dwóch grup', copySummary: 'Kopiuj podsumowanie',
};

export const content = makeEffectContent({ language: 'pl', slug: 'kalkulator-wielkosci-efektu-dwoch-grup', title: 'Kalkulator wielkości efektu dla dwóch grup', description: 'Oblicz d Cohena i g Hedgesa na podstawie podsumowań dwóch niezależnych grup oraz sprawdź kierunek, wielkość i przybliżony 95% przedział ufności.', ui,
  faq: [
    { question: 'Co mierzy d Cohena?', answer: 'd Cohena wyraża różnicę między średnimi dwóch grup w jednostkach połączonego odchylenia standardowego. Znak zachowuje kierunek A minus B, a wartość bezwzględna opisuje wielkość standaryzowaną.' },
    { question: 'Dlaczego pokazujemy g Hedgesa obok d Cohena?', answer: 'g Hedgesa stosuje korektę dla małych prób do d Cohena. Przy dużych grupach jest ona niewielka, a przy małej liczbie połączonych stopni swobody bardziej zauważalna.' },
    { question: 'Czy przedział obejmujący zero dowodzi braku efektu?', answer: 'Nie. Oznacza, że przybliżony przedział 95% zawiera zero, więc kierunek nie jest precyzyjnie określony na tym poziomie ufności. Nie dowodzi równoważności ani braku efektu.' },
    { question: 'Czy kalkulator zastępuje test t lub metaanalizę?', answer: 'Nie. Oblicza standaryzowane różnice średnich z podsumowań statystycznych. Nie testuje hipotez, nie sprawdza założeń ani nie łączy badań.' },
  ],
  howTo: [
    { name: 'Wprowadź podsumowania grup', text: 'Wpisz średnią, odchylenie standardowe z próby i liczebność każdej grupy. Użyj tej samej skali pomiaru i ustal kolejność A oraz B.' },
    { name: 'Odczytaj różnicę standaryzowaną', text: 'Użyj d Cohena jako bezpośredniego oszacowania oraz g Hedgesa jako wersji skorygowanej dla małych prób. Wynik zachowuje kierunek A minus B.' },
    { name: 'Sprawdź precyzję i kontekst', text: 'Czytaj przybliżony 95% przedział ufności razem z etykietą wielkości. Próg jest orientacyjną konwencją, a nie uniwersalną regułą ważności praktycznej.' },
  ],
  introTitle: 'Wystandaryzuj różnicę przed interpretacją', introOne: 'Surowa różnica średnich zależy od pierwotnej skali pomiaru. Ten <strong>kalkulator wielkości efektu dla dwóch grup</strong> dzieli różnicę przez połączone odchylenie standardowe, aby wyrazić ją w jednostkach odchylenia standardowego.', introTwo: 'Wprowadź średnią, odchylenie standardowe z próby i liczebność dla dwóch niezależnych grup. Narzędzie zwraca d Cohena, skorygowane dla małych prób g Hedgesa, przybliżone przedziały 95% i kierunek A minus B.', calculationTitle: 'Co wykorzystuje obliczenie', tableHeaders: ['Wynik', 'Jak go czytać'], tableRows: [['Różnica średnich', 'Oryginalna różnica A minus B w jednostkach pomiaru.'], ['Połączone odchylenie standardowe', 'Wspólne rozproszenie użyte do standaryzacji różnicy.'], ['d Cohena', 'Różnica standaryzowana przed korektą dla małych prób.'], ['g Hedgesa', 'd Cohena pomnożone przez korektę opartą na połączonych stopniach swobody.'], ['Przybliżony przedział 95%', 'Zakres precyzji oparty na podsumowaniach i przybliżeniu normalnym.']], directionTitle: 'Jak czytać kierunek', direction: 'Znak ma znaczenie. Wartość dodatnia oznacza, że średnia A jest większa niż B; ujemna oznacza odwrotną relację. Zamiana etykiet odwraca znak, ale nie wartość bezwzględną.', actions: ['Utrzymuj obie grupy na tej samej skali pomiaru.', 'Używaj odchyleń z próby, nie błędów standardowych.', 'Sprawdź niezależność obserwacji.', 'Podaj oszacowanie, przedział, kolejność grup i jednostki.'], thresholdTitle: 'Progi nie są werdyktami', threshold: 'Etykiety bardzo mała, mała, średnia i duża opierają się na popularnych punktach odniesienia około 0,2, 0,5 i 0,8. Znaczenie praktyczne zależy od wyniku, jakości pomiaru, projektu i najmniejszej istotnej różnicy.', precisionTitle: 'Precyzja jest częścią wyniku', precision: 'Duża różnica standaryzowana z szerokim przedziałem może być nieprecyzyjna, szczególnie przy małych lub zmiennych grupach. Jeśli przedział g Hedgesa obejmuje zero, kierunek jest niepewny na tym przybliżonym poziomie ufności.', glossaryTitle: 'Słownik', glossary: [['Połączone odchylenie standardowe', 'Oszacowanie wspólnego rozproszenia dwóch niezależnych grup dostosowane do liczebności prób.'], ['d Cohena', 'Różnica średnich podzielona przez połączone odchylenie standardowe.'], ['g Hedgesa', 'Skorygowana pod kątem obciążenia małych prób wersja różnicy standaryzowanej.'], ['Przedział ufności', 'Zakres pokazujący niepewność oszacowania, a nie gwarancja dotycząca stałego parametru.']], limitsTitle: 'Czego narzędzie nie może powiedzieć', limits: 'Kalkulator nie potwierdza przyczynowości, istotności statystycznej, równoważności, znaczenia klinicznego, normalności, równości wariancji ani jakości badania. Nie obsługuje obserwacji sparowanych ani informacji utraconych przy samych statystykach podsumowujących.',
});
