import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Grupo A', groupB: 'Grupo B', mean: 'Média', standardDeviation: 'Desvio padrão amostral', sampleSize: 'Tamanho da amostra', meanHelp: 'Resultado médio deste grupo.', standardDeviationHelp: 'Use o DP amostral, não o erro padrão.', sampleSizeHelp: 'Pelo menos 2 observações.', example: 'Usar exemplo', reset: 'Redefinir', clear: 'Limpar entradas', resultTitle: 'Leitura do efeito', difference: 'Diferença das médias A menos B', pooledStandardDeviation: 'DP combinado', degreesOfFreedom: 'Graus de liberdade', cohensD: "d de Cohen", hedgesG: "g de Hedges", correction: 'Correção para amostras pequenas', confidenceInterval: 'IC de 95% aprox.', magnitude: 'Magnitude', direction: 'Direção', uncertainty: 'Precisão', higher: 'O grupo A é maior', lower: 'O grupo A é menor', equal: 'As médias são iguais', verySmall: 'Muito pequena', small: 'Pequena', medium: 'Média', large: 'Grande', crossesZero: 'O intervalo cruza zero', doesNotCrossZero: 'O intervalo não cruza zero', chartTitle: 'A diferença em uma escala comum', chartDifference: 'Diferença bruta', chartBand: 'Intervalo de g de Hedges', chartBaseline: 'Médias iguais', chartA: 'Média do grupo A', chartB: 'Média do grupo B', chartEmpty: 'Insira seis valores válidos para ver a diferença calibrada.', statusReady: 'Atualizado com os valores acima.', statusInvalid: 'Verifique os seis campos: os DP devem ser positivos e os tamanhos de amostra pelo menos 2.', statusCopied: 'Resumo copiado.', copied: 'Copiado', inputError: 'Entrada inválida', summaryTitle: 'Resumo do tamanho do efeito de dois grupos', copySummary: 'Copiar resumo',
};

export const content = makeEffectContent({ language: 'pt', slug: 'calculadora-tamanho-efeito-dois-grupos', title: 'Calculadora do tamanho do efeito de dois grupos', description: 'Calcule d de Cohen e g de Hedges a partir dos resumos de dois grupos independentes e examine direção, magnitude e intervalo de confiança aproximado de 95%.', ui,
  faq: [
    { question: 'O que mede o d de Cohen?', answer: 'O d de Cohen expressa a diferença entre duas médias em unidades de desvio padrão combinado. O sinal mantém a direção A menos B e o valor absoluto descreve a magnitude padronizada.' },
    { question: 'Por que mostrar g de Hedges além de d de Cohen?', answer: 'O g de Hedges aplica uma correção para amostras pequenas ao d de Cohen. A correção é pequena em grupos grandes e mais visível quando os graus de liberdade combinados são baixos.' },
    { question: 'Um intervalo que cruza zero prova que não existe efeito?', answer: 'Não. Significa que o intervalo aproximado de 95% inclui zero e que os dados resumidos não localizam a direção com precisão nesse nível de confiança. Não prova equivalência nem ausência.' },
    { question: 'Esta calculadora substitui um teste t ou uma meta-análise?', answer: 'Não. Ela calcula diferenças padronizadas entre médias usando estatísticas resumidas. Não testa hipóteses, verifica pressupostos, modela dados pareados nem combina estudos.' },
  ],
  howTo: [
    { name: 'Insira os resumos dos dois grupos', text: 'Insira a média, o desvio padrão amostral e o tamanho de cada grupo. Use a mesma escala de medida e defina A e B antes de interpretar o sinal.' },
    { name: 'Leia a diferença padronizada', text: 'Use d de Cohen para a estimativa direta e g de Hedges para a estimativa corrigida para amostras pequenas. O resultado mantém a direção A menos B.' },
    { name: 'Verifique precisão e contexto', text: 'Leia o intervalo aproximado de 95% junto com a categoria de magnitude. Um limiar é uma convenção orientativa, não uma regra universal de importância prática.' },
  ],
  introTitle: 'Padronize a diferença antes de interpretá-la', introOne: 'Uma diferença bruta entre médias depende da escala de medida original. Esta <strong>calculadora do tamanho do efeito de dois grupos</strong> divide a diferença pelo desvio padrão combinado para expressar a distância em unidades de desvio padrão.', introTwo: 'Insira os resumos de dois grupos independentes: média, desvio padrão amostral e tamanho da amostra. A ferramenta retorna d de Cohen, g de Hedges corrigido para amostras pequenas, intervalos aproximados de 95% e a direção A menos B.', calculationTitle: 'O que o cálculo usa', tableHeaders: ['Resultado', 'Como ler'], tableRows: [['Diferença das médias', 'A diferença original A menos B nas unidades de medida.'], ['Desvio padrão combinado', 'A dispersão comum usada para colocar a diferença em uma escala padronizada.'], ['d de Cohen', 'A diferença padronizada antes da correção para amostras pequenas.'], ['g de Hedges', 'd de Cohen multiplicado por uma correção baseada nos graus de liberdade combinados.'], ['Intervalo aproximado de 95%', 'Uma faixa de precisão baseada nos resumos e em uma aproximação normal.']], directionTitle: 'Como ler a direção', direction: 'O sinal é importante. Um valor positivo indica que a média de A é maior que a de B; um valor negativo indica o contrário. Inverter os grupos inverte o sinal, mas não a magnitude absoluta.', actions: ['Mantenha os dois grupos na mesma escala de medida.', 'Use desvios padrão amostrais, não erros padrão.', 'Verifique se as observações são independentes.', 'Relate estimativa, intervalo, ordem dos grupos e unidades.'], thresholdTitle: 'Limiares não são veredictos', threshold: 'As etiquetas muito pequena, pequena, média e grande seguem referências comuns perto de 0,2, 0,5 e 0,8. A importância prática depende do resultado, da qualidade da medida, do desenho e da menor diferença relevante.', precisionTitle: 'A precisão também faz parte do resultado', precision: 'Uma diferença padronizada grande com intervalo amplo ainda pode ser imprecisa, especialmente com grupos pequenos ou variáveis. Se o intervalo de g de Hedges cruzar zero, trate a direção como incerta nesse nível aproximado de confiança.', glossaryTitle: 'Glossário', glossary: [['Desvio padrão combinado', 'Estimativa da dispersão comum de dois grupos independentes ajustada ao tamanho das amostras.'], ['d de Cohen', 'Diferença das médias dividida pelo desvio padrão combinado.'], ['g de Hedges', 'Versão da diferença padronizada corrigida pelo viés de amostras pequenas.'], ['Intervalo de confiança', 'Faixa que mostra a incerteza da estimativa, não uma garantia sobre um parâmetro fixo.']], limitsTitle: 'O que esta ferramenta não pode dizer', limits: 'A calculadora não estabelece causalidade, significância estatística, equivalência, importância clínica, normalidade, igualdade de variâncias ou qualidade do estudo. Também não aceita observações pareadas nem recupera informação perdida em estatísticas resumidas.',
});
