import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Grupp A', groupB: 'Grupp B', mean: 'Medelvärde', standardDeviation: 'Stickprovsstandardavvikelse', sampleSize: 'Stickprovsstorlek', meanHelp: 'Genomsnittligt resultat i gruppen.', standardDeviationHelp: 'Använd stickprovets SD, inte standardfelet.', sampleSizeHelp: 'Minst 2 observationer.', example: 'Använd exempel', reset: 'Återställ', clear: 'Rensa indata', resultTitle: 'Effekttolkning', difference: 'Medelskillnad A minus B', pooledStandardDeviation: 'Poolad SD', degreesOfFreedom: 'Frihetsgrader', cohensD: "Cohens d", hedgesG: "Hedges g", correction: 'Korrigering för små stickprov', confidenceInterval: 'Ungefärligt 95 % KI', magnitude: 'Storlek', direction: 'Riktning', uncertainty: 'Precision', higher: 'Grupp A är högre', lower: 'Grupp A är lägre', equal: 'Medelvärdena är lika', verySmall: 'Mycket liten', small: 'Liten', medium: 'Medelstor', large: 'Stor', crossesZero: 'Intervallet korsar noll', doesNotCrossZero: 'Intervallet korsar inte noll', chartTitle: 'Skillnaden på en gemensam skala', chartDifference: 'Rå skillnad', chartBand: 'Hedges g-intervall', chartBaseline: 'Lika medelvärden', chartA: 'Grupp A:s medelvärde', chartB: 'Grupp B:s medelvärde', chartEmpty: 'Ange sex giltiga värden för att se den kalibrerade skillnaden.', statusReady: 'Uppdaterad med värdena ovan.', statusInvalid: 'Kontrollera de sex fälten: SD måste vara positiva och stickproven minst 2.', statusCopied: 'Sammanfattningen kopierades.', copied: 'Kopierad', inputError: 'Ogiltig inmatning', summaryTitle: 'Sammanfattning av effektstorlek för två grupper', copySummary: 'Kopiera sammanfattning',
};

export const content = makeEffectContent({ language: 'sv', slug: 'effektstorlek-tva-grupper-kalkylator', title: 'Kalkylator för effektstorlek mellan två grupper', description: 'Beräkna Cohens d och Hedges g från sammanfattningar av två oberoende grupper och granska riktning, storlek och ett ungefärligt 95-procentigt konfidensintervall.', ui,
  faq: [
    { question: 'Vad mäter Cohens d?', answer: 'Cohens d uttrycker skillnaden mellan två gruppmedelvärden i enheter av poolad standardavvikelse. Tecknet visar riktningen A minus B och absolutvärdet den standardiserade storleken.' },
    { question: 'Varför visas Hedges g tillsammans med Cohens d?', answer: 'Hedges g korrigerar Cohens d för små stickprov. Korrigeringen är liten för stora grupper men tydligare när de sammanlagda frihetsgraderna är få.' },
    { question: 'Bevisar ett intervall som korsar noll att effekten saknas?', answer: 'Nej. Det betyder att det ungefärliga 95-procentiga intervallet innehåller noll och att riktningen inte bestäms exakt på denna konfidensnivå. Det bevisar varken ekvivalens eller frånvaro.' },
    { question: 'Kan kalkylatorn ersätta ett t-test eller en metaanalys?', answer: 'Nej. Den beräknar standardiserade medelskillnader från sammanfattande statistik. Den testar inga hypoteser, kontrollerar inga antaganden och kombinerar inga studier.' },
  ],
  howTo: [
    { name: 'Ange sammanfattningarna för båda grupperna', text: 'Ange medelvärde, stickprovsstandardavvikelse och storlek för varje grupp. Använd samma mätskala och definiera A och B innan tecknet tolkas.' },
    { name: 'Läs den standardiserade skillnaden', text: 'Använd Cohens d för den direkta skattningen och Hedges g för korrigeringen vid små stickprov. Resultatet behåller riktningen A minus B.' },
    { name: 'Granska precision och sammanhang', text: 'Läs det ungefärliga 95-procentiga intervallet tillsammans med storlekskategorin. Ett tröskelvärde är en riktlinje, inte en universell regel för praktisk betydelse.' },
  ],
  introTitle: 'Standardisera skillnaden innan du tolkar den', introOne: 'En rå skillnad mellan medelvärden beror på den ursprungliga mätskalan. Den här <strong>kalkylatorn för effektstorlek mellan två grupper</strong> delar skillnaden med den poolade standardavvikelsen och uttrycker avståndet i standardavvikelseenheter.', introTwo: 'Ange medelvärde, stickprovsstandardavvikelse och storlek för två oberoende grupper. Verktyget returnerar Cohens d, Hedges g korrigerat för små stickprov, ungefärliga 95-procentiga intervall och riktningen A minus B.', calculationTitle: 'Vad beräkningen använder', tableHeaders: ['Utdata', 'Så läser du den'], tableRows: [['Medelskillnad', 'Den ursprungliga skillnaden A minus B i mätenheterna.'], ['Poolad standardavvikelse', 'Den gemensamma spridningen som används för att standardisera skillnaden.'], ['Cohens d', 'Den standardiserade skillnaden före korrigering för små stickprov.'], ['Hedges g', 'Cohens d multiplicerat med en korrigering från de sammanlagda frihetsgraderna.'], ['Ungefärligt 95-procentigt intervall', 'Ett precisionsintervall baserat på sammanfattningarna och en normalapproximation.']], directionTitle: 'Så läser du riktningen', direction: 'Tecknet är viktigt. Ett positivt värde betyder att A har ett högre medelvärde än B; ett negativt värde betyder det motsatta. Om grupperna byts ändras tecknet men inte absolutvärdet.', actions: ['Använd samma mätskala för båda grupperna.', 'Använd stickprovs-SD, inte standardfel.', 'Kontrollera att observationerna är oberoende.', 'Rapportera skattning, intervall, gruppordning och enheter.'], thresholdTitle: 'Trösklar är inga domslut', threshold: 'Etiketterna mycket liten, liten, medelstor och stor följer vanliga riktmärken kring 0,2, 0,5 och 0,8. Praktisk betydelse beror på utfall, mätkvalitet, studiedesign och den minsta relevanta skillnaden.', precisionTitle: 'Precision är en del av resultatet', precision: 'En stor standardiserad skillnad med ett brett intervall kan fortfarande vara oprecis, särskilt för små eller varierande grupper. Om Hedges g-intervall korsar noll är riktningen osäker på denna ungefärliga konfidensnivå.', glossaryTitle: 'Ordlista', glossary: [['Poolad standardavvikelse', 'En skattning av den gemensamma spridningen i två oberoende grupper, justerad för stickprovsstorlek.'], ['Cohens d', 'Medelskillnaden dividerad med den poolade standardavvikelsen.'], ['Hedges g', 'En standardiserad medelskillnad korrigerad för snedvridning i små stickprov.'], ['Konfidensintervall', 'Ett intervall som visar osäkerhet kring skattningen, inte en garanti för en fast parameter.']], limitsTitle: 'Vad verktyget inte kan säga', limits: 'Kalkylatorn fastställer inte kausalitet, statistisk signifikans, ekvivalens, klinisk betydelse, normalitet, lika varianser eller studiekvalitet. Den stöder inte parade observationer eller information som saknas när endast sammanfattande statistik finns.',
});
