import { makeEffectContent } from './localized';
import type { EffectSizeUI } from '../ui';

const ui: EffectSizeUI = {
  groupA: 'Grup A', groupB: 'Grup B', mean: 'Ortalama', standardDeviation: 'Örneklem standart sapması', sampleSize: 'Örneklem büyüklüğü', meanHelp: 'Bu grubun ortalama sonucu.', standardDeviationHelp: 'Standart hata değil, örneklem standart sapması kullanın.', sampleSizeHelp: 'En az 2 gözlem.', example: 'Örnek kullan', reset: 'Sıfırla', clear: 'Girdileri temizle', resultTitle: 'Etkiyi yorumlama', difference: 'Ortalama farkı A eksi B', pooledStandardDeviation: 'Birleştirilmiş SS', degreesOfFreedom: 'Serbestlik derecesi', cohensD: 'Cohen d', hedgesG: 'Hedges g', correction: 'Küçük örneklem düzeltmesi', confidenceInterval: 'Yaklaşık %95 güven aralığı', magnitude: 'Büyüklük', direction: 'Yön', uncertainty: 'Kesinlik', higher: 'Grup A daha yüksek', lower: 'Grup A daha düşük', equal: 'Ortalamalar eşit', verySmall: 'Çok küçük', small: 'Küçük', medium: 'Orta', large: 'Büyük', crossesZero: 'Aralık sıfırı kesiyor', doesNotCrossZero: 'Aralık sıfırı kesmiyor', chartTitle: 'Ortak ölçekte fark', chartDifference: 'Ham fark', chartBand: 'Hedges g aralığı', chartBaseline: 'Eşit ortalamalar', chartA: 'Grup A ortalaması', chartB: 'Grup B ortalaması', chartEmpty: 'Farkı görmek için altı geçerli değer girin.', statusReady: 'Yukarıdaki değerlerden güncellendi.', statusInvalid: 'Altı alanı kontrol edin: SS pozitif, büyüklükler en az 2 olmalıdır.', statusCopied: 'Özet kopyalandı.', copied: 'Kopyalandı', inputError: 'Geçersiz değer', summaryTitle: 'İki grup etki büyüklüğü özeti', copySummary: 'Özeti kopyala',
};

export const content = makeEffectContent({ language: 'tr', slug: 'iki-grup-etki-buyuklugu-hesaplayici', title: 'İki Grup Etki Büyüklüğü Hesaplayıcısı', description: 'İki bağımsız grubun özetlerinden Cohen d ve Hedges g değerlerini hesaplayın; yönü, büyüklüğü ve yaklaşık %95 güven aralığını yorumlayın.', ui,
  faq: [
    { question: 'Cohen d neyi ölçer?', answer: 'Cohen d, iki ortalama arasındaki farkı birleştirilmiş standart sapma birimleriyle ifade eder. İşaret A eksi B yönünü korur, mutlak değer standartlaştırılmış büyüklüğü gösterir.' },
    { question: 'Hedges g neden gösterilir?', answer: 'Hedges g, Cohen d için küçük örneklem düzeltmesi uygular. Büyük gruplarda düzeltme küçüktür; serbestlik derecesi azaldığında daha görünür olur.' },
    { question: 'Sıfırı kesen aralık etki olmadığını kanıtlar mı?', answer: 'Hayır. Yaklaşık %95 aralık sıfırı içerir ve bu güven düzeyinde yön kesin değildir. Bu durum eşdeğerliği veya yokluğu kanıtlamaz.' },
    { question: 'Bu araç t testinin veya meta-analizin yerini tutar mı?', answer: 'Hayır. Yalnızca özet istatistiklerden standartlaştırılmış farkı hesaplar; hipotez testi veya çalışma birleştirmesi yapmaz.' },
  ],
  howTo: [
    { name: 'İki grubun özetlerini girin', text: 'Her grup için ortalama, örneklem standart sapması ve büyüklüğü girin. Aynı ölçeği kullanın ve işareti okumadan önce A ile B\u0027yi belirleyin.' },
    { name: 'Standartlaştırılmış farkı okuyun', text: 'Doğrudan tahmin için Cohen d, küçük örneklem düzeltmeli tahmin için Hedges g kullanın. Sonuç A eksi B yönünü korur.' },
    { name: 'Kesinliği ve bağlamı kontrol edin', text: 'Yaklaşık %95 aralığı büyüklük kategorisiyle birlikte okuyun. Eşik bir kılavuzdur, evrensel bir kural değildir.' },
  ],
  introTitle: 'Yorumlamadan önce farkı standartlaştırın', introOne: 'Ham ortalama farkı ilk ölçüm ölçeğine bağlıdır. Bu <strong>iki grup etki büyüklüğü hesaplayıcısı</strong> farkı birleştirilmiş standart sapmaya bölerek standart sapma birimleriyle ifade eder.', introTwo: 'İki bağımsız grup için ortalama, örneklem standart sapması ve büyüklüğü girin. Araç Cohen d, düzeltilmiş Hedges g, yaklaşık %95 aralıkları ve A eksi B yönünü verir.', calculationTitle: 'Hesaplama ne kullanır?', tableHeaders: ['Çıktı', 'Nasıl okunur'], tableRows: [['Ortalama farkı', 'Ölçüm birimlerindeki özgün A eksi B farkı.'], ['Birleştirilmiş standart sapma', 'Farkı standartlaştırmak için kullanılan ortak yayılım.'], ['Cohen d', 'Küçük örneklem düzeltmesinden önceki standartlaştırılmış fark.'], ['Hedges g', 'Birleşik serbestlik derecelerine dayalı düzeltilmiş Cohen d.'], ['Yaklaşık %95 aralık', 'Özet verilere ve normal yaklaşımına dayalı kesinlik aralığı.']], directionTitle: 'Yön nasıl okunur?', direction: 'İşaret anlamlıdır. Pozitif değer A ortalamasının B\u0027den büyük olduğunu, negatif değer küçük olduğunu gösterir. Grupları ters çevirmek işareti değiştirir, mutlak büyüklüğü değiştirmez.', actions: ['İki grubu aynı ölçüm ölçeğinde tutun.', 'Standart hata değil, örneklem SS kullanın.', 'Gözlemlerin bağımsızlığını kontrol edin.', 'Tahmini, aralığı, grup sırasını ve birimleri raporlayın.'], thresholdTitle: 'Eşikler hüküm değildir', threshold: 'Çok küçük, küçük, orta ve büyük etiketleri 0,2, 0,5 ve 0,8 çevresindeki yaygın referansları izler. Pratik önem sonuca, ölçüm kalitesine, tasarıma ve önemli en küçük farka bağlıdır.', precisionTitle: 'Kesinlik sonucun parçasıdır', precision: 'Geniş aralıklı büyük bir standartlaştırılmış fark yine de kesin olmayabilir; özellikle gruplar küçük veya değişkense. Hedges g aralığı sıfırı keserse yön bu yaklaşık güven düzeyinde belirsizdir.', glossaryTitle: 'Sözlük', glossary: [['Birleştirilmiş standart sapma', 'İki bağımsız grubun ortak yayılımının örneklem büyüklüklerine göre ayarlanmış tahmini.'], ['Cohen d', 'Ortalama farkının birleştirilmiş standart sapmaya bölümü.'], ['Hedges g', 'Küçük örneklem yanlılığı için düzeltilmiş standartlaştırılmış ortalama farkı.'], ['Güven aralığı', 'Tahmin çevresindeki belirsizliği gösteren aralık; sabit bir parametre garantisi değildir.']], limitsTitle: 'Bu araç neyi söyleyemez?', limits: 'Hesaplayıcı nedensellik, istatistiksel anlamlılık, eşdeğerlik, klinik önem, normallik, eşit varyans veya çalışma kalitesini göstermez. Eşleştirilmiş gözlemleri desteklemez.',
});
