import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'perzentilrang-rechner',
  title: 'Perzentilrang Rechner online',
  description: 'Ermittle die Position eines Werts in deinem Datensatz mit einem transparenten Rechner für Perzentilränge. Wähle die Behandlung von Bindungen und sieh Ergebnis, Nachbarn und Einordnung sofort.',
  ui: makeUi(['Perzentilrang', 'Deine Stichprobe', 'z. B. 12, 18, 21, 21, 27, 34, 41, 50', 'Gib mindestens 2 Zahlen ein, getrennt durch Kommas, Leerzeichen, Semikolons oder Zeilenumbrüche.', 'Zielwert', 'z. B. 34', 'Methode bei Gleichständen', 'Darunter (streng)', 'Darunter oder gleich', 'Mittlerer Rang (halbe Gleichstände)', 'Lege fest, wie Beobachtungen gleich dem Zielwert zum Prozentsatz beitragen.', 'Beispiel laden', 'Löschen', 'Position in deiner Stichprobe', 'Perzentilrang', 'Sortierte Position', 'von', 'Unter dem Zielwert', 'Gleich dem Zielwert', 'Über dem Zielwert', 'Niedriger Nachbar', 'Höherer Nachbar', 'Bereich gleicher Positionen', 'Sortierte Stichprobe', 'Niedrigster', 'Höchster', 'Gib Stichprobe und Zielwert ein, um die sortierte Stichprobe zu sehen.', 'Gib mindestens 2 gültige Zahlen ein.', 'Gib einen gültigen numerischen Zielwert ein.', '{n} ungültige Eingabe(n) wurden ignoriert.', 'Der Zielwert steht an Position {position} von {total}. {below} Beobachtung(en) liegen darunter, {equal} sind gleich und {above} liegen darüber. Mit {method} entspricht das dem {percentile}. Perzentil dieser Stichprobe.', 'Zusammenfassung für deine Notizen', 'Zusammenfassung kopieren', 'Kopiert!']),
  faq: makeFaq([
    ['Was bedeutet ein Perzentilrang?', 'Der Perzentilrang beschreibt den Anteil der Beobachtungen unter, bei oder teilweise bis zu einem Zielwert. Er zeigt die Position in dieser Stichprobe und ist keine Wahrscheinlichkeit für das Auftreten des Werts.'],
    ['Welche Methode für Gleichstände soll ich wählen?', 'Darunter zählt nur kleinere Werte. Darunter oder gleich zählt gleiche Werte vollständig. Der mittlere Rang zählt die Gleichstände zur Hälfte. Die gewählte Formel steht neben dem Ergebnis.'],
    ['Wie behandelt der Rechner gleiche Werte?', 'Er zeigt die Anzahl gleicher Beobachtungen und den gesamten Positionsbereich. So bleibt sichtbar, wie jeder Gleichstand den Rang beeinflusst.'],
    ['Beweist ein Perzentilrang statistische Signifikanz?', 'Nein. Das Ergebnis beschreibt nur eine Position in deinen eingegebenen Werten. Es testet keine Hypothese und verallgemeinert nicht automatisch auf eine Population.'],
  ]),
  howTo: makeHowTo([['Stichprobe einfügen', 'Gib Zahlen aus derselben Messung und demselben Kontext ein. Kommas, Leerzeichen, Semikolons und Zeilenumbrüche werden akzeptiert.'], ['Zielwert eingeben', 'Trage den Wert ein, dessen Position du verstehen möchtest. Er darf in der Stichprobe vorkommen oder zwischen zwei Beobachtungen liegen.'], ['Methode auswählen', 'Wähle Darunter, Darunter oder gleich oder mittlerer Rang und lies Prozentwert, Position, Nachbarn und Zählungen ab.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Perzentile', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Perzentil', url: 'https://de.wikipedia.org/wiki/Perzentil' }],
  seo: {
    titles: ['Einen Wert im Zusammenhang sehen', 'Was der Rechner anzeigt', 'So verändern Gleichstände das Ergebnis', 'Grenzen der Interpretation'],
    paragraphs: ['Eine Punktzahl oder Messung lässt sich besser einordnen, wenn ihre Position in der zugrunde liegenden Stichprobe sichtbar ist. Dieser <strong>Perzentilrang-Rechner</strong> sortiert deine Werte, findet den Zielwert und macht die Auswirkung der gewählten Gleichstandsmethode nachvollziehbar.', 'Bei zehn Beobachtungen mit drei kleineren und zwei gleichen Werten liefert die strenge Methode 30 %, die inklusive Methode 50 % und der mittlere Rang 40 %. Keine Variante ist immer richtig: Entscheidend ist, ob gleiche Werte gar nicht, vollständig oder zur Hälfte zählen sollen.', 'Der Rechner schätzt keine Verteilung, kein Konfidenzintervall und keine statistische Signifikanz. Ein hoher Rang kann auch aus einer kleinen oder verzerrten Stichprobe stammen. Für Aussagen über eine Grundgesamtheit brauchst du Kontext und ein passendes inferenzstatistisches Verfahren.'],
    stats: ['Gleichstandsmethoden', 'Daten bleiben lokal', 'Klare Positionsübersicht'],
    tableHeaders: ['Ausgabe', 'Warum sie wichtig ist'],
    tableRows: [['<strong>Perzentilrang</strong>', 'Die Zielposition als Prozentsatz dieser Stichprobe.'], ['<strong>Positionsbereich</strong>', 'Die 1-basierte Position inklusive aller gleichen Werte.'], ['<strong>Darunter / gleich / darüber</strong>', 'Zählungen, mit denen du das Ergebnis prüfen kannst.'], ['<strong>Nachbarn</strong>', 'Die nächstkleinere und nächstgrößere Beobachtung.']],
    tipTitle: 'Eine vergleichbare Stichprobe verwenden',
    tipHtml: 'Ein Perzentil ist nur relativ zu den eingegebenen Werten sinnvoll. Vermische daher nicht unterschiedliche Einheiten, Populationen, Zeiträume oder Messregeln in einer Stichprobe.',
    glossary: [['Stichprobe', 'Die endliche Liste eingegebener Beobachtungen; das Ergebnis beschreibt nur diese Liste.'], ['Perzentilrang', 'Ein beschreibender Prozentsatz, der einen Zielwert in einer sortierten Stichprobe verortet.'], ['Gleichstand', 'Eine oder mehrere Beobachtungen mit exakt demselben Wert wie das Ziel.'], ['Mittlerer Rang', 'Eine Regel, bei der die Hälfte gleicher Beobachtungen gezählt wird.']],
  },
});
