import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'calculadora-rango-percentil',
  title: 'Calculadora de rango percentil online',
  description: 'Descubre dónde se sitúa un valor dentro de tu conjunto de datos con una calculadora transparente de rango percentil. Pega una muestra, elige el método para empates y consulta la posición al instante.',
  ui: makeUi(['Rango percentil', 'Tu muestra', 'p. ej. 12, 18, 21, 21, 27, 34, 41, 50', 'Pega al menos 2 números separados por comas, espacios, punto y coma o saltos de línea.', 'Valor objetivo', 'p. ej. 34', 'Método para empates', 'Por debajo (estricto)', 'Por debajo o igual', 'Rango medio (mitad de los empates)', 'Elige cómo contribuyen al porcentaje las observaciones iguales al objetivo.', 'Cargar ejemplo', 'Borrar', 'Posición en tu muestra', 'Rango percentil', 'Posición ordenada', 'de', 'Por debajo del objetivo', 'Igual al objetivo', 'Por encima del objetivo', 'Vecino inferior', 'Vecino superior', 'Intervalo de posiciones empatadas', 'Mapa de muestra ordenada', 'Mínimo', 'Máximo', 'Introduce una muestra y un objetivo para ver el mapa ordenado.', 'Introduce al menos 2 valores numéricos válidos.', 'Introduce un objetivo numérico válido.', 'Se ignoraron {n} entrada(s) no válida(s).', 'El objetivo está en la posición {position} de {total}. Hay {below} observación(es) por debajo, {equal} iguales y {above} por encima. Con {method}, representa el percentil {percentile} de esta muestra.', 'Resumen para tus notas', 'Copiar resumen', '¡Copiado!']),
  faq: makeFaq([['¿Qué significa el rango percentil?', 'Describe qué parte de las observaciones queda por debajo, hasta el valor o a mitad de los empates, según el método elegido. Indica una posición en esta muestra; no es la probabilidad de que ocurra el valor.'], ['¿Qué método para empates debo elegir?', 'Usa Por debajo para contar solo valores menores, Por debajo o igual para contar los iguales por completo y Rango medio para repartir los empates a la mitad.'], ['¿Cómo se tratan los empates?', 'La calculadora muestra cuántas observaciones son iguales y el intervalo completo de posiciones empatadas. Así puedes revisar el efecto de la repetición.'], ['¿El rango percentil demuestra significación estadística?', 'No. Es una descripción dentro de los valores introducidos. No estima un parámetro poblacional, no contrasta hipótesis ni prueba significación estadística.']]),
  howTo: makeHowTo([['Pega tu muestra', 'Introduce números de la misma medición y contexto, separados por comas, espacios, punto y coma o saltos de línea.'], ['Introduce el objetivo', 'Escribe el valor cuya posición quieres entender. Puede aparecer en la muestra o quedar entre dos observaciones.'], ['Elige un método', 'Selecciona Por debajo, Por debajo o igual o Rango medio y revisa porcentaje, posición, vecinos y recuentos.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentil', url: 'https://es.wikipedia.org/wiki/Percentil' }],
  seo: {
    titles: ['Mira el valor dentro de su contexto', 'Qué muestra la calculadora', 'Cómo cambian los empates el resultado', 'Límites de interpretación'],
    paragraphs: ['Una puntuación, medida u observación se entiende mejor cuando puedes ver su lugar dentro de la muestra que la generó. Esta <strong>calculadora de rango percentil</strong> ordena tus valores, localiza el objetivo y explica cómo cambia la respuesta al elegir otro tratamiento de empates.', 'Imagina diez observaciones: tres están por debajo del objetivo y dos son iguales. Por debajo devuelve 30 %, Por debajo o igual devuelve 50 % y Rango medio devuelve 40 %. Ninguna opción es universalmente correcta; depende de cómo quieras contar los valores iguales.', 'La herramienta no estima una distribución, un intervalo de confianza, una probabilidad ni la significación estadística. Un percentil alto también puede proceder de una muestra pequeña o sesgada. Usa contexto y un método inferencial adecuado si quieres generalizar más allá de los datos introducidos.'],
    stats: ['Métodos de empate', 'Datos sin servidor', 'Resumen de posición'],
    tableHeaders: ['Resultado', 'Por qué importa'],
    tableRows: [['<strong>Rango percentil</strong>', 'La posición del objetivo expresada como porcentaje de esta muestra.'], ['<strong>Intervalo de posición</strong>', 'La posición basada en uno, incluido el rango completo de empates.'], ['<strong>Por debajo / igual / por encima</strong>', 'Recuentos que hacen transparente el cálculo.'], ['<strong>Vecinos</strong>', 'Las observaciones inferior y superior más cercanas.']],
    tipTitle: 'Mantén comparable la muestra',
    tipHtml: 'Un percentil solo tiene sentido en relación con los valores introducidos. No mezcles unidades, poblaciones, periodos ni reglas de medición diferentes en una misma muestra.',
    glossary: [['Muestra', 'La lista finita de observaciones introducidas; todos los resultados describen únicamente esa lista.'], ['Rango percentil', 'Porcentaje descriptivo que sitúa un objetivo dentro de una muestra ordenada.'], ['Empate', 'Una o varias observaciones exactamente iguales al valor objetivo.'], ['Rango medio', 'Convención que cuenta la mitad de las observaciones empatadas.']],
  },
});
