import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'calculateur-rang-percentile',
  title: 'Calculateur de rang percentile en ligne',
  description: 'Situez une valeur dans votre ensemble de données grâce à un calculateur de rang percentile transparent. Collez un échantillon, choisissez la méthode pour les ex æquo et consultez le résultat immédiatement.',
  ui: makeUi(['Rang percentile', 'Votre échantillon', 'ex. 12, 18, 21, 21, 27, 34, 41, 50', 'Collez au moins 2 nombres séparés par des virgules, espaces, points-virgules ou retours à la ligne.', 'Valeur cible', 'ex. 34', 'Méthode pour les ex æquo', 'Inférieur (strict)', 'Inférieur ou égal', 'Rang médian (moitié des ex æquo)', 'Choisissez comment les observations égales à la cible contribuent au pourcentage.', 'Charger un exemple', 'Effacer', 'Position dans votre échantillon', 'Rang percentile', 'Position triée', 'sur', 'Inférieur à la cible', 'Égal à la cible', 'Supérieur à la cible', 'Voisin inférieur', 'Voisin supérieur', 'Intervalle des positions ex æquo', 'Carte de l\x27échantillon trié', 'Minimum', 'Maximum', 'Saisissez un échantillon et une cible pour voir la carte triée.', 'Saisissez au moins 2 valeurs numériques valides.', 'Saisissez une cible numérique valide.', '{n} entrée(s) non valide(s) ignorée(s).', 'La cible est en position {position} sur {total}. {below} observation(s) sont inférieures, {equal} égales et {above} supérieures. Avec {method}, cela correspond au {percentile}e percentile de cet échantillon.', 'Résumé pour vos notes', 'Copier le résumé', 'Copié !']),
  faq: makeFaq([['Que signifie le rang percentile ?', 'Le rang percentile décrit la part des observations inférieures, inférieures ou égales, ou située au milieu des ex æquo selon la méthode choisie. Il indique une position dans cet échantillon, et non la probabilité d\x27observer la valeur.'], ['Quelle méthode choisir pour les ex æquo ?', 'Inférieur compte uniquement les valeurs plus petites, Inférieur ou égal compte entièrement les valeurs égales, et Rang médian en compte la moitié. La formule choisie est affichée avec le résultat.'], ['Comment les ex æquo sont-ils traités ?', 'Le calculateur affiche le nombre de valeurs égales et l\x27intervalle complet de leurs positions. Vous pouvez ainsi vérifier l\x27effet de chaque répétition.'], ['Le rang percentile prouve-t-il une signification statistique ?', 'Non. C\x27est une description de la position dans les valeurs saisies. Il ne teste pas une hypothèse et ne permet pas, à lui seul, de généraliser à une population.']]),
  howTo: makeHowTo([['Collez votre échantillon', 'Saisissez des nombres issus de la même mesure et du même contexte, séparés par des virgules, espaces, points-virgules ou retours à la ligne.'], ['Saisissez la cible', 'Entrez la valeur dont vous voulez comprendre la position. Elle peut être présente dans l\x27échantillon ou entre deux observations.'], ['Choisissez une méthode', 'Sélectionnez Inférieur, Inférieur ou égal ou Rang médian, puis lisez le percentile, la position, les voisins et les compteurs.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipédia: Percentile', url: 'https://fr.wikipedia.org/wiki/Percentile' }],
  seo: {
    titles: ['Voir une valeur dans son contexte', 'Ce que montre le calculateur', 'L\x27effet des ex æquo sur le résultat', 'Limites de l\x27interprétation'],
    paragraphs: ['Une note, une mesure ou une observation devient plus facile à interpréter lorsque sa place dans l\x27échantillon d\x27origine est visible. Ce <strong>calculateur de rang percentile</strong> trie vos valeurs, localise la cible et explique l\x27effet de la méthode choisie pour les ex æquo.', 'Avec dix observations, dont trois inférieures et deux égales à la cible, la méthode stricte donne 30 %, la méthode inclusive 50 % et le rang médian 40 %. Aucune formule n\x27est toujours la bonne: le choix dépend de la façon dont vous souhaitez compter les valeurs égales.', 'Cet outil n\x27estime ni une distribution, ni un intervalle de confiance, ni une probabilité, ni une signification statistique. Un percentile élevé peut venir d\x27un échantillon très petit ou biaisé. Utilisez le contexte et une méthode inférentielle adaptée pour dépasser les données saisies.'],
    stats: ['Méthodes d\x27ex æquo', 'Données locales', 'Résumé de position'],
    tableHeaders: ['Résultat', 'Pourquoi c\x27est utile'],
    tableRows: [['<strong>Rang percentile</strong>', 'La position de la cible exprimée en pourcentage de cet échantillon.'], ['<strong>Intervalle de position</strong>', 'La position à partir de 1, avec toute l\x27étendue en cas d\x27ex æquo.'], ['<strong>Inférieur / égal / supérieur</strong>', 'Des compteurs qui rendent le calcul facile à vérifier.'], ['<strong>Voisins</strong>', 'Les observations inférieure et supérieure les plus proches.']],
    tipTitle: 'Gardez un échantillon comparable',
    tipHtml: 'Un percentile n\x27a de sens que par rapport aux valeurs saisies. Ne mélangez pas des unités, populations, périodes ou règles de mesure différentes dans un même échantillon.',
    glossary: [['Échantillon', 'La liste finie des observations saisies ; les résultats décrivent uniquement cette liste.'], ['Rang percentile', 'Pourcentage descriptif qui situe une cible dans un échantillon ordonné.'], ['Ex æquo', 'Une ou plusieurs observations exactement égales à la cible.'], ['Rang médian', 'Convention qui compte la moitié des observations ex æquo.']],
  },
});
