import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'kalkulator-peringkat-persentil',
  title: 'Kalkulator peringkat persentil online',
  description: 'Temukan posisi sebuah nilai dalam kumpulan data dengan kalkulator peringkat persentil yang transparan. Tempelkan sampel, pilih metode nilai sama, lalu lihat peringkat dan tetangga nilainya.',
  ui: makeUi(['Peringkat persentil', 'Sampel Anda', 'mis. 12, 18, 21, 21, 27, 34, 41, 50', 'Masukkan sedikitnya 2 angka yang dipisahkan koma, spasi, titik koma, atau baris baru.', 'Nilai target', 'mis. 34', 'Metode nilai sama', 'Di bawah (ketat)', 'Di bawah atau sama dengan', 'Peringkat tengah (setengah nilai sama)', 'Pilih cara observasi yang sama dengan target berkontribusi pada persentase.', 'Muat contoh', 'Hapus', 'Posisi dalam sampel Anda', 'Peringkat persentil', 'Posisi terurut', 'dari', 'Di bawah target', 'Sama dengan target', 'Di atas target', 'Tetangga bawah', 'Tetangga atas', 'Rentang posisi sama', 'Peta sampel terurut', 'Terendah', 'Tertinggi', 'Masukkan sampel dan target untuk melihat peta sampel terurut.', 'Masukkan sedikitnya 2 nilai angka yang valid.', 'Masukkan target angka yang valid.', '{n} masukan tidak valid diabaikan.', 'Target berada pada posisi {position} dari {total}. Ada {below} observasi di bawah, {equal} yang sama, dan {above} di atas. Dengan {method}, target berada pada persentil {percentile} dalam sampel ini.', 'Ringkasan untuk catatan Anda', 'Salin ringkasan', 'Tersalin!']),
  faq: makeFaq([['Apa arti peringkat persentil?', 'Peringkat persentil menunjukkan bagian observasi yang berada di bawah target, sampai target, atau di tengah nilai yang sama sesuai metode yang dipilih. Ini menunjukkan posisi dalam sampel, bukan peluang target akan terjadi.'], ['Metode apa yang sebaiknya dipilih?', 'Pilih Di bawah untuk nilai yang lebih kecil saja, Di bawah atau sama dengan untuk menghitung semua nilai yang sama, atau Peringkat tengah untuk menghitung setengahnya.'], ['Bagaimana nilai yang sama ditangani?', 'Kalkulator menampilkan jumlah observasi yang sama serta rentang posisinya. Dengan begitu pengaruh nilai berulang dapat diperiksa.'], ['Apakah peringkat persentil membuktikan signifikansi statistik?', 'Tidak. Hasil ini hanya menggambarkan posisi dalam nilai yang dimasukkan. Ini bukan uji hipotesis dan tidak otomatis mewakili populasi yang lebih luas.']]),
  howTo: makeHowTo([['Tempelkan sampel', 'Gunakan angka dari pengukuran dan konteks yang sama. Pemisah koma, spasi, titik koma, dan baris baru semuanya didukung.'], ['Masukkan target', 'Ketik nilai yang posisinya ingin dipahami. Nilai itu boleh ada di dalam sampel atau berada di antara dua observasi.'], ['Pilih metode', 'Pilih Di bawah, Di bawah atau sama dengan, atau Peringkat tengah. Baca persentase, posisi, tetangga, dan jumlahnya.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Persentil', url: 'https://id.wikipedia.org/wiki/Persentil' }],
  seo: {
    titles: ['Lihat nilai dalam konteksnya', 'Yang ditampilkan kalkulator', 'Pengaruh nilai sama terhadap hasil', 'Batasan interpretasi'],
    paragraphs: ['Nilai ujian, pengukuran, atau observasi lebih mudah dipahami saat posisinya terlihat di dalam sampel asal. <strong>Kalkulator peringkat persentil</strong> ini mengurutkan nilai Anda, menemukan target, dan memperlihatkan bagaimana metode nilai sama mengubah jawabannya.', 'Misalnya ada sepuluh observasi, tiga lebih kecil dari target dan dua sama dengan target. Metode Di bawah menghasilkan 30%, Di bawah atau sama dengan menghasilkan 50%, sedangkan Peringkat tengah menghasilkan 40%. Pilihan yang tepat bergantung pada aturan analisis Anda.', 'Alat ini tidak memperkirakan distribusi, interval kepercayaan, peluang, atau signifikansi statistik. Persentil tinggi dapat berasal dari sampel kecil atau bias. Gunakan konteks bidang dan metode inferensial yang sesuai bila ingin menarik kesimpulan di luar data ini.'],
    stats: ['Metode nilai sama', 'Data tetap lokal', 'Ringkasan posisi'],
    tableHeaders: ['Keluaran', 'Manfaatnya'],
    tableRows: [['<strong>Peringkat persentil</strong>', 'Posisi target yang dinyatakan sebagai persentase sampel.'], ['<strong>Rentang posisi</strong>', 'Posisi mulai dari 1, termasuk semua posisi yang sama.'], ['<strong>Di bawah / sama / di atas</strong>', 'Jumlah yang membuat perhitungan mudah diverifikasi.'], ['<strong>Tetangga</strong>', 'Observasi terdekat yang lebih rendah dan lebih tinggi.']],
    tipTitle: 'Gunakan sampel yang sebanding',
    tipHtml: 'Persentil hanya bermakna dibandingkan dengan nilai yang dimasukkan. Jangan mencampur satuan, populasi, periode, atau aturan pengukuran yang berbeda.',
    glossary: [['Sampel', 'Daftar terbatas berisi observasi yang Anda masukkan; hasil hanya menjelaskan daftar ini.'], ['Peringkat persentil', 'Persentase deskriptif untuk menempatkan target dalam sampel terurut.'], ['Nilai sama', 'Satu atau lebih observasi yang persis sama dengan target.'], ['Peringkat tengah', 'Aturan yang menghitung separuh observasi yang sama.']],
  },
});
