import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'calcolatore-rango-percentile',
  title: 'Calcolatore del rango percentile online',
  description: 'Scopri dove si colloca un valore nel tuo insieme di dati con un calcolatore trasparente del rango percentile. Incolla un campione, scegli il metodo per i valori uguali e visualizza subito il risultato.',
  ui: makeUi(['Rango percentile', 'Il tuo campione', 'es. 12, 18, 21, 21, 27, 34, 41, 50', 'Inserisci almeno 2 numeri separati da virgole, spazi, punti e virgola o righe nuove.', 'Valore obiettivo', 'es. 34', 'Metodo per i valori uguali', 'Inferiori (rigoroso)', 'Inferiori o uguali', 'Rango medio (metà dei valori uguali)', 'Scegli come contribuiscono alla percentuale le osservazioni uguali all\x27obiettivo.', 'Carica esempio', 'Cancella', 'Posizione nel tuo campione', 'Rango percentile', 'Posizione ordinata', 'di', 'Inferiori all\x27obiettivo', 'Uguali all\x27obiettivo', 'Superiori all\x27obiettivo', 'Valore vicino inferiore', 'Valore vicino superiore', 'Intervallo delle posizioni uguali', 'Mappa del campione ordinato', 'Minimo', 'Massimo', 'Inserisci campione e obiettivo per vedere la mappa ordinata.', 'Inserisci almeno 2 valori numerici validi.', 'Inserisci un obiettivo numerico valido.', 'Ignorati {n} elemento/i non validi.', 'L\x27obiettivo è alla posizione {position} di {total}. {below} osservazione/i sono inferiori, {equal} uguali e {above} superiori. Con {method}, corrisponde al percentile {percentile} di questo campione.', 'Riepilogo per i tuoi appunti', 'Copia riepilogo', 'Copiato!']),
  faq: makeFaq([['Che cosa significa rango percentile?', 'Descrive la quota di osservazioni inferiori all\x27obiettivo, inferiori o uguali, oppure a metà dei valori uguali, secondo il metodo scelto. Indica una posizione nel campione e non la probabilità che l\x27obiettivo si verifichi.'], ['Quale metodo devo scegliere?', 'Usa Inferiori per contare solo i valori minori, Inferiori o uguali per contare interamente i valori uguali, oppure Rango medio per contarne la metà.'], ['Come vengono gestiti i valori uguali?', 'Il calcolatore mostra il numero di osservazioni uguali e l\x27intervallo completo delle loro posizioni, così l\x27effetto dei pareggi è verificabile.'], ['Il rango percentile dimostra la significatività statistica?', 'No. È una descrizione della posizione nei valori inseriti. Non verifica ipotesi e non consente da solo di generalizzare a una popolazione.']]),
  howTo: makeHowTo([['Incolla il campione', 'Inserisci numeri provenienti dalla stessa misurazione e dallo stesso contesto, separati da virgole, spazi, punti e virgola o righe nuove.'], ['Inserisci l\x27obiettivo', 'Scrivi il valore di cui vuoi capire la posizione. Può essere presente nel campione o trovarsi tra due osservazioni.'], ['Scegli un metodo', 'Seleziona Inferiori, Inferiori o uguali o Rango medio, poi leggi percentile, posizione, vicini e conteggi.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentile', url: 'https://it.wikipedia.org/wiki/Percentile' }],
  seo: {
    titles: ['Vedi il valore nel suo contesto', 'Che cosa mostra il calcolatore', 'Come i valori uguali cambiano il risultato', 'Limiti dell\x27interpretazione'],
    paragraphs: ['Un punteggio, una misura o un\x27osservazione è più facile da interpretare quando ne vedi la posizione nel campione originale. Questo <strong>calcolatore del rango percentile</strong> ordina i tuoi valori, individua l\x27obiettivo e rende chiaro l\x27effetto del metodo scelto per i valori uguali.', 'Con dieci osservazioni, tre inferiori e due uguali all\x27obiettivo, il metodo rigoroso restituisce 30%, quello inclusivo 50% e il rango medio 40%. Nessuna formula è sempre corretta: la scelta dipende da come vuoi conteggiare i valori uguali.', 'Lo strumento non stima distribuzioni, intervalli di confidenza, probabilità o significatività statistica. Un percentile alto può dipendere da un campione piccolo o distorto. Per generalizzare oltre i dati inseriti servono contesto e un metodo inferenziale adeguato.'],
    stats: ['Metodi per i pareggi', 'Dati sempre locali', 'Riepilogo della posizione'],
    tableHeaders: ['Risultato', 'Perché è utile'],
    tableRows: [['<strong>Rango percentile</strong>', 'La posizione dell\x27obiettivo espressa come percentuale del campione.'], ['<strong>Intervallo di posizione</strong>', 'La posizione a partire da 1, includendo tutti i valori uguali.'], ['<strong>Inferiori / uguali / superiori</strong>', 'Conteggi che rendono il calcolo trasparente.'], ['<strong>Valori vicini</strong>', 'Le osservazioni inferiore e superiore più prossime.']],
    tipTitle: 'Mantieni il campione confrontabile',
    tipHtml: 'Un percentile ha senso solo rispetto ai valori inseriti. Non mescolare unità, popolazioni, periodi o regole di misurazione differenti nello stesso campione.',
    glossary: [['Campione', 'L\x27elenco finito delle osservazioni inserite; i risultati descrivono solo questo elenco.'], ['Rango percentile', 'Percentuale descrittiva che colloca un obiettivo in un campione ordinato.'], ['Pareggio', 'Una o più osservazioni esattamente uguali al valore obiettivo.'], ['Rango medio', 'Una convenzione che conta metà delle osservazioni uguali.']],
  },
});
