import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'percentielrang-calculator',
  title: 'Online calculator voor percentielrang',
  description: 'Bepaal waar een waarde in je dataset staat met een transparante calculator voor percentielrangen. Plak een steekproef, kies de methode voor gelijke waarden en bekijk direct rang, buren en uitleg.',
  ui: makeUi(['Percentielrang', 'Je steekproef', 'bijv. 12, 18, 21, 21, 27, 34, 41, 50', 'Plak minstens 2 getallen, gescheiden door komma\x27s, spaties, puntkomma\x27s of regeleinden.', 'Doelwaarde', 'bijv. 34', 'Methode voor gelijke waarden', 'Lager (strikt)', 'Lager of gelijk', 'Middenrang (halve gelijke waarden)', 'Kies hoe waarnemingen die gelijk zijn aan het doel bijdragen aan het percentage.', 'Voorbeeld laden', 'Wissen', 'Positie in je steekproef', 'Percentielrang', 'Gesorteerde positie', 'van', 'Onder doelwaarde', 'Gelijk aan doelwaarde', 'Boven doelwaarde', 'Lagere buur', 'Hogere buur', 'Bereik van gelijke posities', 'Gesorteerde steekproefkaart', 'Laagste', 'Hoogste', 'Voer een steekproef en doelwaarde in om de gesorteerde kaart te zien.', 'Voer minstens 2 geldige getallen in.', 'Voer een geldige numerieke doelwaarde in.', '{n} ongeldige invoer(en) genegeerd.', 'De doelwaarde staat op positie {position} van {total}. {below} waarneming(en) zijn lager, {equal} gelijk en {above} hoger. Met {method} is dit het {percentile}e percentiel van deze steekproef.', 'Samenvatting voor je notities', 'Samenvatting kopiëren', 'Gekopieerd!']),
  faq: makeFaq([['Wat betekent percentielrang?', 'Percentielrang beschrijft welk aandeel van de waarnemingen onder, tot en met, of halverwege gelijke waarden tot een doelwaarde ligt. Het gaat om de positie in deze steekproef, niet om de kans dat de waarde voorkomt.'], ['Welke methode voor gelijke waarden moet ik kiezen?', 'Kies Lager voor alleen kleinere waarden, Lager of gelijk om gelijke waarden volledig mee te tellen, of Middenrang om de helft mee te tellen.'], ['Hoe worden gelijke waarden verwerkt?', 'De calculator toont het aantal gelijke waarnemingen en het volledige bereik van hun posities. Daardoor blijft het effect van een gelijke waarde controleerbaar.'], ['Bewijst percentielrang statistische significantie?', 'Nee. Het resultaat beschrijft alleen een positie in de ingevoerde waarden. Het voert geen hypothesetoets uit en zegt niet automatisch iets over een populatie.']]),
  howTo: makeHowTo([['Plak je steekproef', 'Gebruik getallen uit dezelfde meting en context. Komma\x27s, spaties, puntkomma\x27s en regeleinden worden allemaal ondersteund.'], ['Voer het doel in', 'Typ de waarde waarvan je de positie wilt begrijpen. Die mag in de steekproef staan of tussen twee waarnemingen vallen.'], ['Kies een methode', 'Selecteer Lager, Lager of gelijk of Middenrang en lees percentage, positie, buren en aantallen af.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentiel', url: 'https://nl.wikipedia.org/wiki/Percentiel' }],
  seo: {
    titles: ['Bekijk een waarde in context', 'Wat de calculator laat zien', 'Hoe gelijke waarden het resultaat veranderen', 'Grenzen van de interpretatie'],
    paragraphs: ['Een score, meting of waarneming wordt begrijpelijker wanneer je de plaats binnen de oorspronkelijke steekproef ziet. Deze <strong>calculator voor percentielrang</strong> sorteert je waarden, vindt het doel en maakt zichtbaar hoe de gekozen methode voor gelijke waarden het antwoord verandert.', 'Bij tien waarnemingen, waarvan drie lager en twee gelijk aan het doel zijn, geeft Lager 30%, Lager of gelijk 50% en Middenrang 40%. Geen enkele formule is altijd juist: het hangt af van de vraag of gelijke waarden niet, volledig of half moeten meetellen.', 'Deze tool schat geen verdeling, betrouwbaarheidsinterval, kans of statistische significantie. Een hoog percentiel kan ook ontstaan door een kleine of vertekende steekproef. Gebruik context en een geschikte inferentiële methode als je verder wilt gaan dan de ingevoerde waarden.'],
    stats: ['Methoden voor gelijke waarden', 'Gegevens blijven lokaal', 'Duidelijk positierapport'],
    tableHeaders: ['Uitkomst', 'Waarom dit telt'],
    tableRows: [['<strong>Percentielrang</strong>', 'De doelpositie uitgedrukt als percentage van deze steekproef.'], ['<strong>Positiebereik</strong>', 'De positie vanaf 1, inclusief het volledige bereik bij gelijke waarden.'], ['<strong>Lager / gelijk / hoger</strong>', 'Aantallen waarmee je de uitkomst eenvoudig controleert.'], ['<strong>Buren</strong>', 'De dichtstbijzijnde lagere en hogere waarneming.']],
    tipTitle: 'Houd de steekproef vergelijkbaar',
    tipHtml: 'Een percentiel heeft alleen betekenis ten opzichte van de ingevoerde waarden. Combineer geen verschillende eenheden, populaties, perioden of meetregels in één steekproef.',
    glossary: [['Steekproef', 'De eindige lijst met ingevoerde waarnemingen; alle resultaten beschrijven alleen deze lijst.'], ['Percentielrang', 'Een beschrijvend percentage dat een doel in een geordende steekproef plaatst.'], ['Gelijke waarde', 'Een of meer waarnemingen die exact gelijk zijn aan het doel.'], ['Middenrang', 'Een regel waarbij de helft van de gelijke waarnemingen meetelt.']],
  },
});
