import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'kalkulator-rangi-percentylowego',
  title: 'Kalkulator rangi percentylowej online',
  description: 'Sprawdź położenie wartości w swoim zbiorze danych dzięki przejrzystemu kalkulatorowi rangi percentylowej. Wklej próbę, wybierz sposób obsługi remisów i od razu zobacz wynik oraz sąsiednie wartości.',
  ui: makeUi(['Ranga percentylowa', 'Twoja próba', 'np. 12, 18, 21, 21, 27, 34, 41, 50', 'Wklej co najmniej 2 liczby oddzielone przecinkami, spacjami, średnikami lub znakami nowej linii.', 'Wartość docelowa', 'np. 34', 'Metoda remisów', 'Poniżej (ściśle)', 'Poniżej lub równa', 'Ranga środkowa (połowa remisów)', 'Wybierz, jak obserwacje równe wartości docelowej wpływają na procent.', 'Wczytaj przykład', 'Wyczyść', 'Położenie w Twojej próbie', 'Ranga percentylowa', 'Pozycja po sortowaniu', 'z', 'Poniżej celu', 'Równe celowi', 'Powyżej celu', 'Niższy sąsiad', 'Wyższy sąsiad', 'Zakres pozycji remisu', 'Mapa posortowanej próby', 'Najniższa', 'Najwyższa', 'Wprowadź próbę i cel, aby zobaczyć mapę posortowanych wartości.', 'Wprowadź co najmniej 2 prawidłowe liczby.', 'Wprowadź prawidłową wartość docelową.', 'Pominięto {n} nieprawidłowych danych.', 'Wartość docelowa jest na pozycji {position} z {total}. {below} obserwacji jest niżej, {equal} jest równych, a {above} jest wyżej. Przy metodzie {method} daje to {percentile}. percentyl tej próby.', 'Podsumowanie do notatek', 'Kopiuj podsumowanie', 'Skopiowano!']),
  faq: makeFaq([['Co oznacza ranga percentylowa?', 'Ranga percentylowa opisuje udział obserwacji poniżej celu, do wartości celu albo w połowie remisu, zależnie od wybranej metody. Pokazuje położenie w tej próbie, a nie prawdopodobieństwo wystąpienia celu.'], ['Którą metodę remisów wybrać?', 'Poniżej liczy tylko wartości mniejsze, Poniżej lub równa liczy wartości równe w całości, a Ranga środkowa liczy połowę obserwacji równych.'], ['Jak kalkulator obsługuje remisy?', 'Pokazuje liczbę równych obserwacji oraz pełny zakres ich pozycji. Dzięki temu wpływ powtórzeń można łatwo sprawdzić.'], ['Czy ranga percentylowa dowodzi istotności statystycznej?', 'Nie. To opis położenia w podanych wartościach. Nie jest testem hipotezy i sama nie pozwala wnioskować o całej populacji.']]),
  howTo: makeHowTo([['Wklej próbę', 'Wprowadź liczby z tego samego pomiaru i kontekstu. Obsługiwane są przecinki, spacje, średniki oraz znaki nowej linii.'], ['Wprowadź cel', 'Wpisz wartość, której położenie chcesz zrozumieć. Może znajdować się w próbie albo między dwiema obserwacjami.'], ['Wybierz metodę', 'Wybierz Poniżej, Poniżej lub równa albo Rangę środkową, a następnie odczytaj procent, pozycję, sąsiadów i liczniki.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentyl', url: 'https://pl.wikipedia.org/wiki/Percentyl' }],
  seo: {
    titles: ['Zobacz wartość w odpowiednim kontekście', 'Co pokazuje kalkulator', 'Jak remisy zmieniają wynik', 'Granice interpretacji'],
    paragraphs: ['Wynik, pomiar lub obserwacja jest łatwiejsza do zinterpretowania, gdy widać jej miejsce w próbie, z której pochodzi. Ten <strong>kalkulator rangi percentylowej</strong> sortuje własne wartości, lokalizuje cel i wyjaśnia wpływ wybranej metody remisów.', 'Załóżmy dziesięć obserwacji: trzy są mniejsze od celu, a dwie są z nim równe. Metoda Poniżej daje 30%, Poniżej lub równa 50%, a Ranga środkowa 40%. Żadna formuła nie jest zawsze najlepsza; wybór zależy od zasad analizy.', 'Narzędzie nie estymuje rozkładu, przedziału ufności, prawdopodobieństwa ani istotności statystycznej. Wysoki percentyl może wynikać z małej lub obciążonej próby. Do uogólnień poza podane dane potrzebne są kontekst i odpowiednia metoda wnioskowania.'],
    stats: ['Metody remisów', 'Dane lokalne', 'Czytelne położenie'],
    tableHeaders: ['Wynik', 'Dlaczego ma znaczenie'],
    tableRows: [['<strong>Ranga percentylowa</strong>', 'Położenie celu wyrażone jako procent tej próby.'], ['<strong>Zakres pozycji</strong>', 'Pozycja liczona od 1 wraz z pełnym zakresem remisu.'], ['<strong>Poniżej / równe / powyżej</strong>', 'Liczniki ułatwiające sprawdzenie obliczenia.'], ['<strong>Sąsiedzi</strong>', 'Najbliższa niższa i wyższa obserwacja.']],
    tipTitle: 'Zachowaj porównywalność próby',
    tipHtml: 'Percentyl ma sens tylko względem wprowadzonych wartości. Nie łącz różnych jednostek, populacji, okresów ani zasad pomiaru w jednej próbie.',
    glossary: [['Próba', 'Skończona lista wprowadzonych obserwacji; wyniki opisują tylko tę listę.'], ['Ranga percentylowa', 'Opisowy procent umieszczający cel w uporządkowanej próbie.'], ['Remis', 'Jedna lub więcej obserwacji dokładnie równych wartości docelowej.'], ['Ranga środkowa', 'Konwencja, która uwzględnia połowę równych obserwacji.']],
  },
});
