import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'calculadora-posto-percentil',
  title: 'Calculadora de posto percentil online',
  description: 'Descubra a posição de um valor no seu conjunto de dados com uma calculadora transparente de posto percentil. Cole uma amostra, escolha o método para empates e veja o resultado imediatamente.',
  ui: makeUi(['Posto percentil', 'Sua amostra', 'ex.: 12, 18, 21, 21, 27, 34, 41, 50', 'Cole pelo menos 2 números separados por vírgulas, espaços, ponto e vírgula ou quebras de linha.', 'Valor-alvo', 'ex.: 34', 'Método para empates', 'Abaixo (estrito)', 'Abaixo ou igual', 'Posto médio (metade dos empates)', 'Escolha como as observações iguais ao alvo contribuem para a percentagem.', 'Carregar exemplo', 'Limpar', 'Posição na sua amostra', 'Posto percentil', 'Posição ordenada', 'de', 'Abaixo do alvo', 'Igual ao alvo', 'Acima do alvo', 'Vizinho inferior', 'Vizinho superior', 'Intervalo de posições empatadas', 'Mapa da amostra ordenada', 'Menor', 'Maior', 'Introduza uma amostra e um alvo para ver o mapa ordenado.', 'Introduza pelo menos 2 valores numéricos válidos.', 'Introduza um alvo numérico válido.', '{n} entrada(s) inválida(s) ignorada(s).', 'O alvo está na posição {position} de {total}. Há {below} observação(ões) abaixo, {equal} iguais e {above} acima. Com {method}, isso corresponde ao percentil {percentile} desta amostra.', 'Resumo para as suas notas', 'Copiar resumo', 'Copiado!']),
  faq: makeFaq([['O que significa posto percentil?', 'O posto percentil descreve a parte das observações abaixo do alvo, até ao alvo ou a meio dos empates, conforme o método escolhido. Mostra uma posição nesta amostra, não a probabilidade de o alvo ocorrer.'], ['Que método de empates devo escolher?', 'Use Abaixo para contar apenas valores menores, Abaixo ou igual para contar totalmente os valores iguais, ou Posto médio para contar metade dos empates.'], ['Como são tratados os empates?', 'A calculadora mostra o número de observações iguais e o intervalo completo das suas posições, tornando visível o efeito dos valores repetidos.'], ['O posto percentil prova significância estatística?', 'Não. É uma descrição da posição nos valores introduzidos. Não testa uma hipótese nem permite generalizar automaticamente para uma população.']]),
  howTo: makeHowTo([['Cole a sua amostra', 'Introduza números da mesma medição e contexto. São aceites vírgulas, espaços, ponto e vírgula e quebras de linha.'], ['Introduza o alvo', 'Escreva o valor cuja posição pretende compreender. Pode estar na amostra ou entre duas observações.'], ['Escolha um método', 'Selecione Abaixo, Abaixo ou igual ou Posto médio e consulte percentagem, posição, vizinhos e contagens.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentil', url: 'https://pt.wikipedia.org/wiki/Percentil' }],
  seo: {
    titles: ['Veja um valor no seu contexto', 'O que a calculadora apresenta', 'Como os empates alteram o resultado', 'Limites da interpretação'],
    paragraphs: ['Uma pontuação, medição ou observação torna-se mais fácil de interpretar quando a sua posição dentro da amostra original é visível. Esta <strong>calculadora de posto percentil</strong> ordena os seus valores, localiza o alvo e explica o efeito do método escolhido para empates.', 'Com dez observações, três abaixo do alvo e duas iguais, Abaixo devolve 30%, Abaixo ou igual devolve 50% e Posto médio devolve 40%. Nenhuma fórmula é universalmente correta: a escolha depende de como pretende contar os valores iguais.', 'A ferramenta não estima uma distribuição, um intervalo de confiança, uma probabilidade ou significância estatística. Um percentil alto pode resultar de uma amostra pequena ou enviesada. Para generalizar além dos dados, use contexto e um método inferencial adequado.'],
    stats: ['Métodos de empate', 'Dados locais', 'Resumo de posição'],
    tableHeaders: ['Resultado', 'Por que importa'],
    tableRows: [['<strong>Posto percentil</strong>', 'A posição do alvo expressa como percentagem desta amostra.'], ['<strong>Intervalo de posição</strong>', 'A posição a partir de 1, incluindo todo o intervalo em caso de empate.'], ['<strong>Abaixo / igual / acima</strong>', 'Contagens que tornam o cálculo fácil de confirmar.'], ['<strong>Vizinhos</strong>', 'As observações inferior e superior mais próximas.']],
    tipTitle: 'Mantenha a amostra comparável',
    tipHtml: 'Um percentil só é significativo em relação aos valores introduzidos. Não misture unidades, populações, períodos ou regras de medição diferentes na mesma amostra.',
    glossary: [['Amostra', 'A lista finita de observações introduzidas; os resultados descrevem apenas essa lista.'], ['Posto percentil', 'Percentagem descritiva que localiza um alvo numa amostra ordenada.'], ['Empate', 'Uma ou mais observações exatamente iguais ao valor-alvo.'], ['Posto médio', 'Uma convenção que conta metade das observações empatadas.']],
  },
});
