import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'percentilrank-kalkylator',
  title: 'Kalkylator för percentilrank online',
  description: 'Se var ett värde ligger i din datamängd med en tydlig kalkylator för percentilrank. Klistra in ett urval, välj metod för lika värden och se rankning, grannar och förklaring direkt.',
  ui: makeUi(['Percentilrank', 'Ditt urval', 't.ex. 12, 18, 21, 21, 27, 34, 41, 50', 'Klistra in minst 2 tal separerade med kommatecken, blanksteg, semikolon eller radbrytningar.', 'Målvärde', 't.ex. 34', 'Metod för lika värden', 'Under (strikt)', 'Under eller lika med', 'Medianrank (hälften av lika värden)', 'Välj hur observationer som är lika med målet bidrar till procentandelen.', 'Ladda exempel', 'Rensa', 'Position i ditt urval', 'Percentilrank', 'Sorterad position', 'av', 'Under målet', 'Lika med målet', 'Över målet', 'Lägre granne', 'Högre granne', 'Intervall för lika positioner', 'Karta över sorterat urval', 'Lägst', 'Högst', 'Ange urval och mål för att se kartan över det sorterade urvalet.', 'Ange minst 2 giltiga numeriska värden.', 'Ange ett giltigt numeriskt målvärde.', '{n} ogiltig(a) inmatning(ar) ignorerades.', 'Målet ligger på position {position} av {total}. {below} observation(er) ligger under, {equal} är lika och {above} ligger över. Med {method} blir det {percentile} percentilen i detta urval.', 'Sammanfattning för dina anteckningar', 'Kopiera sammanfattning', 'Kopierat!']),
  faq: makeFaq([['Vad betyder percentilrank?', 'Percentilrank beskriver andelen observationer under målet, upp till målet eller mitt bland lika värden, beroende på vald metod. Den visar en position i urvalet och är inte sannolikheten att målet inträffar.'], ['Vilken metod ska jag välja?', 'Välj Under för att räkna enbart mindre värden, Under eller lika med för att räkna lika värden fullt ut, eller Medianrank för att räkna hälften.'], ['Hur hanteras lika värden?', 'Kalkylatorn visar antalet lika observationer och hela intervallet av deras positioner. Det gör effekten av upprepade värden tydlig.'], ['Bevisar percentilrank statistisk signifikans?', 'Nej. Resultatet beskriver bara en position bland de inmatade värdena. Det är inget hypotes-test och gäller inte automatiskt för en hel population.']]),
  howTo: makeHowTo([['Klistra in ditt urval', 'Använd tal från samma mätning och sammanhang. Kommatecken, blanksteg, semikolon och radbrytningar stöds.'], ['Ange målet', 'Skriv värdet vars position du vill förstå. Det kan finnas i urvalet eller ligga mellan två observationer.'], ['Välj en metod', 'Välj Under, Under eller lika med eller Medianrank och läs av procent, position, grannar och antal.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Wikipedia: Percentil', url: 'https://sv.wikipedia.org/wiki/Percentil' }],
  seo: {
    titles: ['Se värdet i sitt sammanhang', 'Det här visar kalkylatorn', 'Så ändrar lika värden resultatet', 'Begränsningar i tolkningen'],
    paragraphs: ['Ett resultat, en mätning eller en observation blir lättare att tolka när dess plats i det ursprungliga urvalet är synlig. Den här <strong>kalkylatorn för percentilrank</strong> sorterar dina värden, hittar målet och visar hur metoden för lika värden påverkar svaret.', 'Med tio observationer, tre under målet och två som är lika, ger Under 30 %, Under eller lika med 50 % och Medianrank 40 %. Ingen formel är alltid rätt; valet beror på om lika värden ska räknas noll, helt eller till hälften.', 'Verktyget uppskattar inte en fördelning, ett konfidensintervall, en sannolikhet eller statistisk signifikans. En hög percentil kan komma från ett litet eller snedvridet urval. För generalisering krävs sammanhang och en lämplig inferentiell metod.'],
    stats: ['Metoder för lika värden', 'Data stannar lokalt', 'Tydlig positionsöversikt'],
    tableHeaders: ['Resultat', 'Varför det är viktigt'],
    tableRows: [['<strong>Percentilrank</strong>', 'Målets position uttryckt som procent av urvalet.'], ['<strong>Positionsintervall</strong>', 'Positionen från 1, inklusive hela intervallet vid lika värden.'], ['<strong>Under / lika / över</strong>', 'Antal som gör beräkningen enkel att kontrollera.'], ['<strong>Grannar</strong>', 'Närmaste lägre och högre observation.']],
    tipTitle: 'Håll urvalet jämförbart',
    tipHtml: 'En percentil är bara meningsfull i relation till de inmatade värdena. Blanda inte olika enheter, populationer, tidsperioder eller mätregler i samma urval.',
    glossary: [['Urval', 'Den ändliga lista med observationer du angav; resultaten beskriver bara denna lista.'], ['Percentilrank', 'En beskrivande procent som placerar ett mål i ett sorterat urval.'], ['Lika värde', 'En eller flera observationer som är exakt lika med målet.'], ['Medianrank', 'En regel där hälften av lika observationer räknas.']],
  },
});
