import { createLocalizedContent, makeFaq, makeHowTo, makeUi } from '../localized';

export const content = createLocalizedContent({
  slug: 'yuzdelik-dilim-sirasi-hesaplama',
  title: 'Çevrim içi yüzdelik dilim sırası hesaplayıcı',
  description: 'Şeffaf bir yüzdelik dilim sırası hesaplayıcı ile bir değerin veri kümenizdeki yerini bulun. Örneklemi yapıştırın, eşit değer yöntemini seçin ve sıralamayı, komşuları ve açıklamayı hemen görün.',
  ui: makeUi(['Yüzdelik dilim sırası', 'Örnekleminiz', 'örn. 12, 18, 21, 21, 27, 34, 41, 50', 'Virgül, boşluk, noktalı virgül veya satır sonlarıyla ayrılmış en az 2 sayı girin.', 'Hedef değer', 'örn. 34', 'Eşit değer yöntemi', 'Altında (kesin)', 'Altında veya eşit', 'Orta sıra (eşitlerin yarısı)', 'Hedefe eşit gözlemlerin yüzdeye nasıl katkı vereceğini seçin.', 'Örneği yükle', 'Temizle', 'Örnekleminizdeki konum', 'Yüzdelik dilim sırası', 'Sıralanmış konum', '/', 'Hedefin altında', 'Hedefe eşit', 'Hedefin üstünde', 'Alt komşu', 'Üst komşu', 'Eşit konum aralığı', 'Sıralı örneklem haritası', 'En düşük', 'En yüksek', 'Sıralı haritayı görmek için örneklem ve hedef girin.', 'En az 2 geçerli sayısal değer girin.', 'Geçerli bir sayısal hedef girin.', '{n} geçersiz giriş yok sayıldı.', 'Hedef {total} içinde {position}. konumdadır. {below} gözlem daha düşük, {equal} eşit ve {above} daha yüksektir. {method} yöntemiyle bu örneklemin yüzdelik dilimi {percentile} olur.', 'Notlarınız için özet', 'Özeti kopyala', 'Kopyalandı!']),
  faq: makeFaq([['Yüzdelik dilim sırası ne anlama gelir?', 'Seçilen yönteme göre hedefin altında, hedefe kadar veya eşit değerlerin ortasında kalan gözlemlerin payını açıklar. Bu örneklemdeki konumu gösterir; hedefin gerçekleşme olasılığı değildir.'], ['Hangi eşit değer yöntemini seçmeliyim?', 'Yalnızca küçük değerleri saymak için Altında, eşitleri tamamen saymak için Altında veya eşit, yarısını saymak için Orta sıra yöntemini kullanın.'], ['Eşit değerler nasıl işlenir?', 'Hesaplayıcı eşit gözlem sayısını ve bunların tüm konum aralığını gösterir. Böylece tekrarların etkisini kontrol edebilirsiniz.'], ['Yüzdelik dilim sırası istatistiksel anlamlılığı kanıtlar mı?', 'Hayır. Sonuç yalnızca girilen değerler içindeki konumu açıklar. Hipotez testi yapmaz ve tek başına bir kitle hakkında genelleme sağlamaz.']]),
  howTo: makeHowTo([['Örnekleminizi yapıştırın', 'Aynı ölçüm ve bağlamdan gelen sayıları kullanın. Virgül, boşluk, noktalı virgül ve satır sonu ayraçları desteklenir.'], ['Hedefi girin', 'Konumunu anlamak istediğiniz değeri yazın. Değer örneklemde bulunabilir veya iki gözlem arasında kalabilir.'], ['Yöntem seçin', 'Altında, Altında veya eşit ya da Orta sıra seçin; yüzdeyi, konumu, komşuları ve sayıları okuyun.']]),
  bibliography: [{ name: 'NIST/SEMATECH: Percentiles', url: 'https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/percenti.htm' }, { name: 'Vikipedi: Yüzdelik dilim', url: 'https://tr.wikipedia.org/wiki/Y%C3%BCzdelik_dilim' }],
  seo: {
    titles: ['Bir değeri bağlamı içinde görün', 'Hesaplayıcının gösterdikleri', 'Eşit değerler sonucu nasıl değiştirir', 'Yorumlamanın sınırları'],
    paragraphs: ['Bir puan, ölçüm veya gözlem, onu üreten örneklem içindeki konumunu gördüğünüzde daha anlaşılır olur. Bu <strong>yüzdelik dilim sırası hesaplayıcı</strong> değerlerinizi sıralar, hedefi bulur ve eşit değer yönteminin yanıtı nasıl değiştirdiğini açıklar.', 'On gözlemden üçü hedeften düşük, ikisi eşitse Altında %30, Altında veya eşit %50, Orta sıra ise %40 verir. Her durumda geçerli tek bir formül yoktur; doğru seçim eşit değerleri hiç, tamamen veya yarım sayma kuralınıza bağlıdır.', 'Bu araç dağılım, güven aralığı, olasılık veya istatistiksel anlamlılık tahmin etmez. Yüksek bir yüzdelik küçük ya da yanlı bir örneklemden kaynaklanabilir. Girilen verilerin ötesine geçmek için bağlam ve uygun çıkarımsal yöntem gerekir.'],
    stats: ['Eşit değer yöntemleri', 'Veriler yerel kalır', 'Açık konum özeti'],
    tableHeaders: ['Çıktı', 'Neden önemli'],
    tableRows: [['<strong>Yüzdelik dilim sırası</strong>', 'Hedef konumunun örneklemin yüzdesi olarak ifadesi.'], ['<strong>Konum aralığı</strong>', 'Eşitliklerde tüm aralıkla birlikte 1\x27den başlayan konum.'], ['<strong>Altında / eşit / üstünde</strong>', 'Sonucu doğrulamayı kolaylaştıran sayılar.'], ['<strong>Komşular</strong>', 'En yakın düşük ve yüksek gözlemler.']],
    tipTitle: 'Karşılaştırılabilir bir örneklem kullanın',
    tipHtml: 'Bir yüzdelik yalnızca girilen değerlerle ilişkili olarak anlamlıdır. Aynı örneklemde farklı birimleri, kitleleri, dönemleri veya ölçüm kurallarını karıştırmayın.',
    glossary: [['Örneklem', 'Girdiğiniz sonlu gözlem listesi; tüm sonuçlar yalnızca bu listeyi açıklar.'], ['Yüzdelik dilim sırası', 'Hedefi sıralı bir örneklemde konumlandıran açıklayıcı yüzde.'], ['Eşit değer', 'Hedef değerle tam olarak aynı olan bir veya daha fazla gözlem.'], ['Orta sıra', 'Eşit gözlemlerin yarısını sayan kural.']],
  },
});
